### ISSUE TITLE
cannot install 

### ISSUE THREAD

**Issue by fedono** [Quorafind/Obsidian-Memos#101]
awesome project but I cannot install 

![image](https://user-images.githubusercontent.com/12681297/151313455-1d7fa78a-7288-4f88-80d0-aee8e1732838.png)

**Comment by Quorafind** [comment]
Can you manually install it and then try to update it in next version?

**Comment by Quorafind** [comment]
Oh, I do know why this happened, could you install the lastest version of Obsidian ,and then try to install this again? Because I set minAppVersion to 0.13.14, which means that you should have installed at least 0.13.14 ver of Obsidian.

**Comment by fedono** [comment]
update obsidian to the latest version and then install is ok, thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
