### ISSUE TITLE
background color of sidebar(heatmap) doesn't fit with theme

### ISSUE THREAD

**Issue by heddxh** [Quorafind/Obsidian-Memos#103]
![Screenshot_20220128-101958](https://user-images.githubusercontent.com/63106571/151476072-bff0f43c-901f-4513-bed6-60dc2ae8f81b.png)
 
If i remember correctly，it only happens on the latest version.

add: on obsidian android app

**Comment by Quorafind** [comment]
I didn't change color of sidebar after 1.4.0 , did you have same issue when you used 1.6.0 ?

**Comment by heddxh** [comment]
> I didn't change color of sidebar after 1.4.0 , did you have same issue when you used 1.6.0 ?

same problem in 1.6.1

**Comment by Quorafind** [comment]
I used the `#000000` as the color of the sidebar. If you want to change it, change color here and add it to your snippet or theme.
```
@media only screen and (max-width: 875px) {
  .theme-dark .memos-sidebar-wrapper {
      background-color: #000000 !important;
  }
}
```

**Comment by heddxh** [comment]
thanks!
and what about the background of taga zone?
![Screenshot_20220128-182852](https://user-images.githubusercontent.com/63106571/151531236-f12d1407-d963-4c8f-9df7-3181032c6bb2.png)

**Comment by kalmir** [comment]
Try the same as above, except this time you would use `.tags-wrapper`.

If you like customising stuff, it is definitely worth learning to use Developer Toolbar (Ctrl+Shift+I) to find the css classes you need to target.

**Comment by heddxh** [comment]
oh , thanks very much!
