### ISSUE TITLE
Link to original note

### ISSUE THREAD

**Issue by javiavid** [Quorafind/Obsidian-Memos#11]
It would be useful to be able to go to the original note, to make a more complete edition.
I suggest CTRL+click on the date to open in obsidian the original note.

![image](https://user-images.githubusercontent.com/7627504/148213909-26615e18-5c0a-4f59-8524-6a57a3035bac.png)

**Comment by Quorafind** [comment]
Now you could Ctrl+Click on memo to go to original note #13  . It should make sense before 2.0.0

**Comment by javiavid** [comment]
I didn't know it was possible, I just checked it in the new version.
I think that's enough. Thank you!
