### ISSUE TITLE
可能存在清空当日日记的问题。

### ISSUE THREAD

**Issue by xpmax2022** [Quorafind/Obsidian-Memos#110]
我的 obsidian设置是开启后默认打开当天的日记，如果我在 memos 里面删除一条记录，然后退出再重新打开 obsidian，当天的日记内容就全部没有了。关闭插件后，不会出现清空日记的情况。能否检查一下插件删除记录的相关操作吗？

**Comment by Quorafind** [comment]
需要解释的是，你删除的是当天的memos还是过去的memos，另外，有尝试过在空白的库中是否能复现？

**Comment by xpmax2022** [comment]
感谢这么快就回复！我新建一个测试空白库，删memo后，没有出现清空日记文件现象，但是有如下提示，我是一个 obsidian 新手，不知道哪里设置有问题。
![Snipaste_2022-02-08_09-28-02](https://user-images.githubusercontent.com/98856346/152900542-1147c5e8-d193-45a7-ab86-de1f1ecdcbdc.jpg)

**Comment by Quorafind** [comment]
你这个问题出现的情况好像是，因为你没有这个文件的读写权限，经常出现在网盘同步或者权限不足的情况，你可以检查一下是不是自己的网盘同步？

**Comment by xpmax2022** [comment]
主库是网盘同步的，没有这个提示。测试库是本地盘的，空间富余，反而每次删除就会出现提示。
想起来了，之前是删除 带有 todo checkbox 标志的记录后，再启动ob，日记就清空了。

**Comment by Quorafind** [comment]
所以是 todo checkbox 的 memo 才会导致这种情况是吗？如果是的话，我这边检查一下是不是在识别上有这个问题

**Comment by xpmax2022** [comment]
是的。很好用的插件，希望能修复一下😀。

**Comment by Quorafind** [comment]
会的，等我复现一下这个 BUG，看看是什么导致的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月9日(周三) 下午5:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Quorafind/Obsidian-Memos] 可能存在清空当日日记的问题。 (Issue #110)




 
是的。很好用的插件，希望能修复一下😀。

**Comment by xpmax2022** [comment]
今天又出现一次日记清空的情况 。。
这次没有删除任何 memo 记录，只是编辑了一条常规记录（带有加粗文字的记录），关闭 ob ，再开启的时候，记录就没有了。
可以复现。

**Comment by xpmax2022** [comment]
具体操作，我在 日记 里面，把一段文字加粗，关掉 ob ，再开，这个日记就清空了。

**Comment by Quorafind** [comment]
能否录一下屏，而且按一下 Ctrl+Shift+i 将控制台信息发一下给我

**Comment by Quorafind** [comment]
https://user-images.githubusercontent.com/13215013/153326036-586a4389-fd81-4639-8566-60fdde671314.mp4

我认为这个是源自 Ob 自身的 Bug，不管关闭 Memos 与否，都会触发类似的崩溃然后丢失文件

**Comment by xpmax2022** [comment]
![Snipaste_2022-02-10_10-37-01](https://user-images.githubusercontent.com/98856346/153326567-e52ea53b-98db-4415-953b-6f1972b833e7.jpg)

**Comment by xpmax2022** [comment]
https://user-images.githubusercontent.com/98856346/153326598-bfd77571-a068-4c20-9652-ceff7e66ea3f.mp4

**Comment by xpmax2022** [comment]
不是插件的问题就好😀，希望 ob 更新后能避免这个问题。
我也是 flomoapp 的注册用户。用了你这个插件后，flomoapp 沦落为资料收集器了😂

**Comment by Quorafind** [comment]
刚刚询问了，上述的问题是因为如果在 Ob 保存文件的时候关闭的话，系统会杀死这个进程，从而导致对应的文件内容出错，所以最好的避免方式是在输入或者更改后，不要立马就重启 Obsidian

**Comment by xpmax2022** [comment]
学到了，错怪了，谢谢！可以放心大胆的用了😀
