### ISSUE TITLE
与Periodic Notes插件的兼容问题。

### ISSUE THREAD

**Issue by Awyugan** [Quorafind/Obsidian-Memos#12]
1.目前，只能输入YYYY-MM-DD格式的日记。
2. 输入的内容只会从第一行开始。不能设置在某个## 标题下面

**Comment by Quorafind** [comment]
1 你尝试去日记中设定不同的日记格式
2 在新版中修复

**Comment by Quorafind** [comment]
在设置中默认有一个 Insert After 的选项，在里面填入自己的标题

**Comment by Awyugan** [comment]
> 在设置中默认有一个 Insert After 的选项，在里面填入自己的标题

这个我没设置好，谢谢。期待支持新的日记格式

**Comment by Quorafind** [comment]
已修复。
