### ISSUE TITLE
可以把memo写入到指定的文件么？

### ISSUE THREAD

**Issue by shanyang121** [Quorafind/Obsidian-Memos#133]
现在写一条memo好像默认添加到当天的日记中，虽然可以选择添加到哪个标题下，但是想通过捷径直接添加到每天对应的标题下比较麻烦。可不可以选择添加memo到一个固定的md文件中，这样就可以同时用捷径往里添加内容而不用打开OBsidian软件再添加。
另外十分感谢开发者开发的这个插件，确实很好用。

**Comment by Quorafind** [comment]
正在考虑如何解决时间戳的问题，目前想到的方案是同一个文件，然后每个标题采用对应的日期，下边依然是小时分钟的形式

**Comment by Quorafind** [comment]
你现在可以采用 1.9.0 里面的 Dataview 索引，虽然暂时无法支持写入到其它文件，但是支持了你索引其它文件。

**Comment by shanyang121** [comment]
您说的是这个选项么？
![image](https://user-images.githubusercontent.com/80085868/163906676-8ca4c017-143e-4ad7-b5ec-2d52c93358b7.png)
我在icloud obsidian的文件夹（iCloud~md~obsidian\shanyang\06-memos）里建了个memos.md的文件,我直接在这里填入
\shanyang\06-memos\memos.md, 然后在这个memos.md里写东西好像不能被memos识别。请问是写的东西要用什么固定的格式么？还是我的这个路径填写的有问题。

**Comment by shanyang121** [comment]
> 你现在可以采用 1.9.0 里面的 Dataview 索引，虽然暂时无法支持写入到其它文件，但是支持了你索引其它文件。

您说的是这个选项么？
![image](https://user-images.githubusercontent.com/80085868/163906676-8ca4c017-143e-4ad7-b5ec-2d52c93358b7.png)
我在icloud obsidian的文件夹（`iCloud~md~obsidian\shanyang\06-memos`）里建了个memos.md的文件,在memeos设置里的上面截图位置填写了这个路径`\shanyang\06-memos\memos.md`, 然后我在memos.md里写了点东西（`- 10:22 测试新的momos  2022/4/19`)，打开memos好像不能识别。请问是写的东西要用什么固定的格式么？还是我的这个路径填写的有问题。

**Comment by Quorafind** [comment]
需要你这个文件中有这个标签

**Comment by shanyang121** [comment]
> > 你现在可以采用 1.9.0 里面的 Dataview 索引，虽然暂时无法支持写入到其它文件，但是支持了你索引其它文件。
> 
> 您说的是这个选项么？ ![image](https://user-images.githubusercontent.com/80085868/163906676-8ca4c017-143e-4ad7-b5ec-2d52c93358b7.png) 我在icloud obsidian的文件夹（`iCloud~md~obsidian\shanyang\06-memos`）里建了个memos.md的文件,在memeos设置里的上面截图位置填写了这个路径`\shanyang\06-memos\memos.md`, 然后我在memos.md里写了点东西（`- 10:22 测试新的momos 2022/4/19`)，打开memos好像不能识别。请问是写的东西要用什么固定的格式么？还是我的这个路径填写的有问题。

研究了半天没研究明白dataview

> 需要你这个文件中有这个标签，而且需要 Dataview 版本大于或等于0.5.9
我的dataview是0.5.9
我在这个设置框里输入：`#memo, folder: 06-memos`,然后在06-memos这个文件夹下的memos.md里写点东西 `- 10:22 测试新的momos #memo`, 这样就可以被识别到么？
编程小白对dataview语法不是很明白，哈哈，如果方便还请大神赐教

**Comment by Quorafind** [comment]
参试一下 `#memo AND "06-memos"`，#memos 只要是在这个笔记中的任意地方就行，它就只是索引这个笔记整体。

**Comment by shanyang121** [comment]
> #memo AND "06-memos"

收到，有空试下，感谢作者百忙中的回复

**Comment by shanyang121** [comment]
> 参试一下 `#memo AND "06-memos"`，#memos 只要是在这个笔记中的任意地方就行，它就只是索引这个笔记整体。

刚试了下，我在每天日记的文件夹（每天日记里的memo是可以检索到的）下建了个memos.md 的文件，在里面写了`测试memo #memo`的文本，然后在memo的设置里检索式写的是`#memo AND "memos",我测试了下，是检索不到的。
不知道是不是个别现象，还是memos和我的其他插件配置有冲突。我新提个issue吧，看看是不是还有其他人有这个问题。要是有问题的人多作者在考虑下是不是bug。

**Comment by eatcosmos** [comment]
![image](https://github.com/Quorafind/Obsidian-Memos/assets/83876321/79bf0a90-e052-45ac-ab79-232cd2a51c8b)
![image](https://github.com/Quorafind/Obsidian-Memos/assets/83876321/f2549f75-24a8-44ae-87aa-266c986f8ba6)
