### ISSUE TITLE
输入完想法后，使用CTRL+ENTER快速保存 Use CTRL+ENTER to quickly save the idea after entering it

### ISSUE THREAD

**Issue by MILKMILKKING** [Quorafind/Obsidian-Memos#139]
输入完想法后，使用CTRL+ENTER快速保存。
现在似乎还需要鼠标点击后才能保存。

Use CTRL+ENTER to quickly save the idea after entering it.
It also seems to require a mouse click to save after now.

**Comment by Quorafind** [comment]
去快捷键面板设置 NOTE IT 的快捷键，对应保存

**Comment by MILKMILKKING** [comment]
> 

好的，谢谢你，已经设置了。
