### ISSUE TITLE
如何将生成文件指定在某个文件夹下，而不是在根目录

### ISSUE THREAD

**Issue by fg6062** [Quorafind/Obsidian-Memos#144]
包括 delete 和 query

**Comment by Quorafind** [comment]
目前依赖的是日记文件夹，您可以去设置一下 Obsidian 自带的日记插件，对应地，会将内容放在日记插件中设置的日记文件夹中。

**Comment by fg6062** [comment]
哈哈哈，眼瞎

**Comment by eatcosmos** [comment]
![image](https://github.com/Quorafind/Obsidian-Memos/assets/83876321/074610ad-d8e1-4702-849f-a3b0d417d633)
![image](https://github.com/Quorafind/Obsidian-Memos/assets/83876321/acaf7488-4199-465b-9463-9e1a6de97882)
