### ISSUE TITLE
[feature] 那年今日和每日随机

### ISSUE THREAD

**Issue by SmallPond** [Quorafind/Obsidian-Memos#145]
是否可以考虑通过filter/query或其他方式实现那年今日的 memo 或每日随机一个 memo 呢？

**Comment by Quorafind** [comment]
那年今日可以实现，每日随机的话我这边需要看要用什么方式来实现

**Comment by SmallPond** [comment]
> 那年今日可以实现，每日随机的话我这边需要看要用什么方式来实现

十分期待~

**Comment by SmallPond** [comment]
配合 [v1.9.0](https://github.com/Quorafind/Obsidian-Memos/releases/tag/1.9.0) 版本的 DATE filter + Tags filter 可实现那年今日。

例如： `DATE:BEFORE:last year` 的第一项即那年今日。 但是无法有效过滤仅显示当天的 memos。

尝试使用 `DATE: **BEFORE** :last year`  AND  `DATE: **AFTER** :last year`  会显示无 memos。

**Comment by Quorafind** [comment]
![image](https://user-images.githubusercontent.com/13215013/168023991-ec7f4dbb-68bb-47f6-b002-1eb34d4d7b59.png)
