### ISSUE TITLE
BUG: can not read property 'path' of undefined

### ISSUE THREAD

**Issue by alanbobs999** [Quorafind/Obsidian-Memos#146]
<img width="232" alt="image" src="https://user-images.githubusercontent.com/73283555/159168722-0d524d93-4a59-45bd-ae2a-f6eddf6ba0bb.png">

创建检索式时发生如上错误。

**Comment by Quorafind** [comment]
这个问题出现的情况很罕见，但是一般出现于你没有设置日记文件夹，或者你的日记文件夹中已经有 query.md 这个文件，可以先排查下

**Comment by alanbobs999** [comment]
已经设置日记文件夹，将 query.md 删除之后创建没有错误信息出现，但是只要再次新建检索式就会出现上述错误。而且第一次创建的检索式已经写入 query.md ，但是 Memos 界面中并不能看到。
