### ISSUE TITLE
希望可以支持某些编辑插件：如Auto Link Title

### ISSUE THREAD

**Issue by 3Stoness** [Quorafind/Obsidian-Memos#148]

**Comment by Quorafind** [comment]
因为这些输入组件依赖的是原生的编辑器输入，而目前ob并没有开放其原生的编辑器的操作权限，因此暂时没有办法实现这个功能；还有其它的依赖于 codemirror 实现的一些插件也没办法直接移植过来；

**Comment by juestchaos** [comment]
@3Stoness hi
memos 2.x 版本已经可以支持与 auto link title 联动

效果如下
![Uploading image.png…]()
