### ISSUE TITLE
能否将memos文件保存到固定的文件夹

### ISSUE THREAD

**Issue by lizhendong128** [Quorafind/Obsidian-Memos#157]
我希望在这个库里做很多事，除了生成memos，还要编辑其他文档。
这样的话，希望能将memos保存到固定的文件夹，直观上避免文件目录杂乱
可以在设置里增加这个选项

**Comment by Quorafind** [comment]
重复议题  https://github.com/Quorafind/Obsidian-Memos/issues/144
