### ISSUE TITLE
Issue with hover editor plugin

### ISSUE THREAD

**Issue by laawn** [Quorafind/Obsidian-Memos#161]
When opening the Memos pane in the Hover Editor plugin, attempting to click on the "tag," "photo," or "bullet/task" buttons causes the cursor to change to a magnifier and clicking simply enlarges the window. When the hover editor pane is full-screen, the buttons work fine, aside from still displaying the magnifier cursor. I've attempted to disable all plugins, minus these two, and it still occurs.

**Comment by Quorafind** [comment]
Fixed in #166
