### ISSUE TITLE
1.9.0找不到评论memos功能

### ISSUE THREAD

**Issue by shanyang121** [Quorafind/Obsidian-Memos#168]
更新了1.9.0后没有发现更新介绍里说的评论功能。
更新介绍里显示评论的memo会显示到被评论的memo下
如下图
![image](https://user-images.githubusercontent.com/80085868/163784539-51454ad2-141c-41c5-a8c4-510d399db42f.png)
而我更新了后并没有看到“评论”的按钮，只有这几个：
![image](https://user-images.githubusercontent.com/80085868/163784694-c2624901-9d1d-4859-baee-14b88fb7c4ab.png)
点击“引用”后编辑，显示的是两条memo，如下图，并不是像更新说明里显示的那样：
![image](https://user-images.githubusercontent.com/80085868/163785040-392d174b-dec1-4800-aca1-f51d283a7747.png)
我是win10的平台，有了解的还请赐教

**Comment by shipengfish** [comment]
<img width="929" alt="image" src="https://user-images.githubusercontent.com/7721612/163787454-64bb92db-d1c0-4da2-ad76-f6839b5a6fe7.png">
看看开关是否开启了，另外如果要展示评论，dataview 插件的版本也要最新。

**Comment by shipengfish** [comment]
> 更新了1.9.0后没有发现更新介绍里说的评论功能。
> 更新介绍里显示评论的memo会显示到被评论的memo下
> 如下图
> ![image](https://user-images.githubusercontent.com/80085868/163784539-51454ad2-141c-41c5-a8c4-510d399db42f.png)
> 而我更新了后并没有看到“评论”的按钮，只有这几个：
> ![image](https://user-images.githubusercontent.com/80085868/163784694-c2624901-9d1d-4859-baee-14b88fb7c4ab.png)
> 点击“引用”后编辑，显示的是两条memo，如下图，并不是像更新说明里显示的那样：
> ![image](https://user-images.githubusercontent.com/80085868/163785040-392d174b-dec1-4800-aca1-f51d283a7747.png)
> 我是win10的平台，有了解的还请赐教

看看开关是否开启了，另外如果要展示评论，dataview 插件的版本也要最新。
<img width="935" alt="image" src="https://user-images.githubusercontent.com/7721612/163787655-679ee79a-a16d-42de-9cab-6f8bef3eed8c.png">

**Comment by Quorafind** [comment]
因为没有适配主题的问题，所以你没看到这个图标。更新 1.9.1 再看一下。

**Comment by shanyang121** [comment]
> 因为没有适配主题的问题，所以你没看到这个图标。更新 1.9.1 再看一下。

更新了1.9.1 ，上面您说到的实验特性开启了，点那个对话框可以弹出评论的输入框，但是输入后点发布就会弹出下面的通知，不能评论
![image](https://user-images.githubusercontent.com/80085868/163791125-0e6112d0-271b-468c-937f-accc617b2737.png)

**Comment by Quorafind** [comment]
需要将 dataview 的版本更新到0.5.9

**Comment by shanyang121** [comment]
> 需要将 dataview 的版本更新到0.5.9
点击评论的图标输入评论后，显示下面的通知，无法评论
![image](https://user-images.githubusercontent.com/80085868/163791652-ae5ddfa5-384d-415b-ae82-960a0b419db5.png)
我看插件中心的dataview最新版才0.4.26
这个需要手动去github下载0.5.9版本的dataview么？

**Comment by Quorafind** [comment]
用 https://github.com/TfTHacker/obsidian42-brat 可以方便点，将 Quorafind/Obsidian-Memos 加进去就行了

**Comment by shanyang121** [comment]
> 用 https://github.com/TfTHacker/obsidian42-brat 可以方便点，将 Quorafind/Obsidian-Memos 加进去就行了

哈哈，自己去github下了新版的dateview，目前评论memo已经没有问题了，谢谢大神的指导。

**Comment by shanyang121** [comment]
> 用 https://github.com/TfTHacker/obsidian42-brat 可以方便点，将 Quorafind/Obsidian-Memos 加进去就行了

还有个小问题，就是对memo的评论是可以修改的，但是没有办法对单独的评论进行删除，只能删除整条memo才能删除对应下面的评论
