### ISSUE TITLE
Mobile and Expanded UI version

### ISSUE THREAD

**Issue by javiavid** [Quorafind/Obsidian-Memos#17]
When you are visualizing tickets there is little space to navigate between the tickets, maybe you could reduce the size of the write box (NEW) a little.

If you need to write a longer entry, a button would be fine to expand the writing box (expanded) or even a complete window.

![image](https://user-images.githubusercontent.com/7627504/148260404-d1cd5558-ef69-4bc0-a867-ffca332fc8e4.png)

I do not know if these things are possible in obsidian or if they need a lot of time, they are only suggestions to improve your plugin, I think it's a great contribution to Obsidian.

Thanks for your time

**Comment by Quorafind** [comment]
A new UI should be on the way😂

**Comment by Quorafind** [comment]
Did some ui improvement on mobile.

**Comment by javiavid** [comment]
Thanks, although there are some problems, for example in minimal you can't use the search box.
I guess it is very complicated to work well in all themes. 
Do you recommend any theme for Memos?

**Comment by Quorafind** [comment]
I also used Minimal😂

**Comment by javiavid** [comment]
Although primary is also very good

**Comment by javiavid** [comment]
The text box expands as you type, I don't think this function is necessary.

**Comment by Quorafind** [comment]
@javiavid Do you think I need to add a scroll bar for mobile using? Espescially when typing on mobile

**Comment by javiavid** [comment]
I just tried to write a very long text and I think there is a problem. What you are typing is not being displayed correctly.
Maybe having a scroll bar will solve this.

**Comment by Quorafind** [comment]
Thanks for quick reply 🧐

**Comment by javiavid** [comment]
You're welcome.
You are doing a great job with the plugin, there are many updates.
