### ISSUE TITLE
v1.9 版本分享memo时报错

### ISSUE THREAD

**Issue by Achieve777** [Quorafind/Obsidian-Memos#170]
ob-memos版本: v1.9
ob 版本: v0.14.5

点击 分享memo 之后出现下面的报错
<img width="738" alt="image" src="https://user-images.githubusercontent.com/15379292/163794090-eb4ff39c-fbd6-4599-8bec-b13905abfb09.png">

**Comment by Quorafind** [comment]
请更新至1.9.1

**Comment by Achieve777** [comment]
更新最新版本后问题解决, 感谢作者
