### ISSUE TITLE
关于引用更好展示的建议

### ISSUE THREAD

**Issue by shanyang121** [Quorafind/Obsidian-Memos#173]
1.9.0版本向某条笔记添加引用后显示如下蓝色链接
![image](https://user-images.githubusercontent.com/80085868/163888692-9081cc63-a05d-4ad1-bab6-0d4f89fb0219.png)
如果点击蓝色链接会跳转到错误的应用
但是点击三个点后的阅读选项是可以正确的显示引用链接
想要阅读引用需要点击三个点，再点击“阅读”选项，感觉有点麻烦
可否再评论的按钮旁边加个阅读的按钮，这样感觉会方便点，哈哈。
![image](https://user-images.githubusercontent.com/80085868/163889052-17a1fda5-8040-4f45-abf0-37f131e02cf2.png)

**Comment by hqweay** [comment]
现在点卡片上面的时间是可以直接进阅读界面的。
不过这个链接应该实现个功能，比如跳转到引用对应的阅读界面？@Quorafind

**Comment by shanyang121** [comment]
> 现在点卡片上面的时间是可以直接进阅读界面的。 不过这个链接应该实现个功能，比如跳转到引用对应的阅读界面？@Quorafind

学到了，非常感谢
