### ISSUE TITLE
在插件商店安装时显示“no appropriate version found”

### ISSUE THREAD

**Issue by zhahuya** [Quorafind/Obsidian-Memos#174]
安卓手机，iPad均出现此问题。

**Comment by shanyang121** [comment]
应该是移动端的还没有更新到插件商店里，可以把电脑端的插件文件夹手动复制到手机端的配置文件夹里。

**Comment by zhahuya** [comment]
> 

谢谢，PC上确实可以安装，如果是这样的话，我可以等等再安装。

**Comment by shanyang121** [comment]
> > 应该是移动端的还没有更新到插件商店里，可以把电脑端的插件文件夹手动复制到手机端的配置文件夹里。
> 
> 谢谢，PC上确实可以安装，如果是这样的话，我可以等等再安装。
我直接把PC上更新过的memo插件文件夹拷贝到对应手机OB配置文件的插件文件夹里，目前感觉使用上没有发现什么问题。

**Comment by dzhuyx** [comment]
昨天mac上也有这个问题

**Comment by dzhuyx** [comment]
现在的版本里没有这个问题了

From: Boninall ***@***.***>
Date: Wednesday, April 20, 2022 at 9:37 PM
To: Quorafind/Obsidian-Memos ***@***.***>
Cc: Yuxin(Daisy) Zhu ***@***.***>, Comment ***@***.***>
Subject: Re: [Quorafind/Obsidian-Memos] 在插件商店安装时显示“no appropriate version found” (Issue #174)

神奇的问题，请问现在的版本还有同样的情况吗。

―

**Comment by zhahuya** [comment]
> 神奇的问题，请问现在的版本还有同样的情况吗。

我这里问题依旧，安卓手机和ipad都是。

**Comment by xpmax2022** [comment]
我的 iPhone 也是这样，不过我通过在 win10 上打开 iCloud 上的库，把插件更新再同步回iCloud云盘。

**Comment by Quorafind** [comment]
根据调查，估计是因为 0.14.4 所对应的版本还没有更新到移动端，而 Memos 依赖于这个版本以后的某些特性，所以。。

**Comment by zhahuya** [comment]
> 根据调查，估计是因为 0.14.4 所对应的版本还没有更新到移动端，而 Memos 依赖于这个版本以后的某些特性，所以。。

很合理。我把PC上的直接复制到移动端了，目前使用正常。
不过这样的话，之后是否可以直接在插件商店更新？

**Comment by Quorafind** [comment]
插件商店可以正常更新
