### ISSUE TITLE
从指定的文件中获取memos 无效

### ISSUE THREAD

**Issue by shanyang121** [Quorafind/Obsidian-Memos#176]
我在每天日记的文件夹（每天日记里的memo是可以检索到的）下建了个memos.md 的文件，在里面写了`测试memo #memo`的文本，然后在memo的设置**从指定的文件中获取memos**里检索式写的是`#memo AND "memos"`, 我测试了下，是检索不到的。
不知道是不是个别现象，还是memos和我的其他插件配置有冲突, 还是我的设置语句没写对。朋友们试下，有同样问题的留个言，哈哈，如果是检索语句写的有问题，还请赐教

**Comment by shipengfish** [comment]
> 
我可以检索到，但是存在一点问题。可以看我的截图
<img width="931" alt="image" src="https://user-images.githubusercontent.com/7721612/163928237-fdfe9f3c-fe37-4fa4-8105-0c3c06531703.png">
<img width="545" alt="image" src="https://user-images.githubusercontent.com/7721612/163928466-1de4cace-41fe-4ac7-8479-37fff7739e32.png">

<img width="673" alt="image" src="https://user-images.githubusercontent.com/7721612/163928447-62fd9cb4-0993-4cd8-b86d-c6db3ca64895.png">

**Comment by shanyang121** [comment]
> > 
> 
> 我可以检索到，可以看我的截图。不过时间会失效就是了（问一句：有办法能处理这个时间吗？） <img alt="image" width="931" src="https://user-images.githubusercontent.com/7721612/163928237-fdfe9f3c-fe37-4fa4-8105-0c3c06531703.png"> <img alt="image" width="545" src="https://user-images.githubusercontent.com/7721612/163928466-1de4cace-41fe-4ac7-8479-37fff7739e32.png">
> 
> <img alt="image" width="673" src="https://user-images.githubusercontent.com/7721612/163928447-62fd9cb4-0993-4cd8-b86d-c6db3ca64895.png">

这个时间好像是要自己加的吧？
![image](https://user-images.githubusercontent.com/80085868/163936358-4214d99b-f711-404d-b316-c2e20427c508.png)

你的这个文档是放在根目录的么？
我的都开了，设置和你一样，还是不显示，好奇怪

**Comment by shipengfish** [comment]
> 

老哥可以分享一下吗？

**Comment by shanyang121** [comment]
> 老哥可以分享一下吗？

你去捷径社区里搜 闪念胶囊 安装人数最多的那个，然后把储存到备忘录改成储存到Obsidian文件夹里你要储存的文档就可以了。这个捷径我不知道怎么分享，[尴尬]
这个是通过捷径直接改icloud里的.md文档，然后再用Obsidian去读。可以在锁屏直接输入。
顺便问下，你的text文档是存在什么位置的？我的完全和你的一样，可还是加载不出来。[汗]

**Comment by shipengfish** [comment]
> 

好的，我试下你的方法。test 文件不在根目录，我建了个收纳箱，放在收纳箱里，应该跟目录没关系。`#memo AND "memos"` 会不会你这个语法不对？我直接就是 #memo

**Comment by shipengfish** [comment]
> > 老哥可以分享一下吗？
> 
> 你去捷径社区里搜 闪念胶囊 安装人数最多的那个，然后把储存到备忘录改成储存到Obsidian文件夹里你要储存的文档就可以了。这个捷径我不知道怎么分享，[尴尬] 这个是通过捷径直接改icloud里的.md文档，然后再用Obsidian去读。可以在锁屏直接输入。 顺便问下，你的test文档是存在什么位置的？我的完全和你的一样，可还是加载不出来。[汗]

可以长按快捷指令，然后分享，拷贝 iCloud 链接，这样应该可以分享。

**Comment by shanyang121** [comment]
直接#memo也是搜不出来的，我还在虚拟机里装了个全新的OB只装了memos和dataview像你那样设置也不行，没办法了，不弄了，反正弄好了也没多大用。[大哭]

**Comment by Quorafind** [comment]
dataview 版本多少

**Comment by shanyang121** [comment]
> 可以长按快捷指令，然后分享，拷贝 iCloud 链接，这样应该可以分享。


https://github.com/Quorafind/Obsidian-Memos/issues/176#issuecomment-1102297289
你需要把文本添加到的文件夹、文件替换成你自己要添加文本的位置

**Comment by shanyang121** [comment]
> dataview 版本多少
0.5.13

**Comment by shanyang121** [comment]
> 0.5.13 目前github上最新版
现在好像一打开“从指定文件中获取memos”选项再重新加载memo界面数据就会加载失败，我开关几次试了下，这个选项关着就没问题。
我看新的issue里也有遇到这个问题的了，不知道是哪里的问题@[Quorafind](https://github.com/Quorafind)

**Comment by shanyang121** [comment]
1.9.4版本已经没有问题了

**Comment by joellti** [comment]
> > 
> 
> 我可以检索到，可以看我的截图。不过时间会失效就是了（问一句：有办法能处理这个时间吗？） <img alt="image" width="931" src="https://user-images.githubusercontent.com/7721612/163928237-fdfe9f3c-fe37-4fa4-8105-0c3c06531703.png"> <img alt="image" width="545" src="https://user-images.githubusercontent.com/7721612/163928466-1de4cace-41fe-4ac7-8479-37fff7739e32.png">
> 
> <img alt="image" width="673" src="https://user-images.githubusercontent.com/7721612/163928447-62fd9cb4-0993-4cd8-b86d-c6db3ca64895.png">

我打开了Fetch Memo from Notes以后也遇到一样的问题，显示Invaid date。请问你后来有没有找到解决办法。谢谢
