### ISSUE TITLE
Memos获取失败的问题，回退版本后插件正常工作

### ISSUE THREAD

**Issue by Zhixiaz** [Quorafind/Obsidian-Memos#177]
操作系统： Windows 11
CPU型号：Intel(R) Core(TM) i5-10200H CPU
问题说明：
更新Memos插件1.9.1版本后，发现打开Memos插件会出现“Memos获取失败”的提示，如图

![image](https://user-images.githubusercontent.com/51500882/163957786-c75d1ad9-bbdb-4a86-ab06-2c635599bc99.png)

回退到1.9.0版本也会出现同样的提示。同时插件界面也是全部空白。（空白界面忘记截图了）

将插件版本回退到1.8.1后插件正常。如图
![image](https://user-images.githubusercontent.com/51500882/163958246-8b797285-64f9-486f-b957-3876376f37f2.png)

**Comment by Quorafind** [comment]
和系统关系不大，你是否同时安装了 periodic notes 和 日记插件。

**Comment by shanyang121** [comment]
关闭 允许memos从笔记中获取memo后可以正常加载

**Comment by gongkaizh** [comment]
> 关闭 允许memos从笔记中获取memo后可以正常加载

默认就是关闭的，结果一样，版本更新完后就什么都加载不了了，原来的记录都没法显示，只能回退到1.8.1

**Comment by Zhixiaz** [comment]
> 和系统关系不大，你是否同时安装了 periodic notes 和 日记插件。

的确安装了periodic notes插件与核心的日记插件,是否是periodic插件的冲突?

> > 关闭 允许memos从笔记中获取memo后可以正常加载
> 
> 默认就是关闭的，结果一样，版本更新完后就什么都加载不了了，原来的记录都没法显示，只能回退到1.8.1

我也是这种情况,没有打开"允许memos从笔记中获取memo"选项

**Comment by peonchen** [comment]
> 

居然可以了，谢谢
