### ISSUE TITLE
Cannot read property unsafeCachedData of null

### ISSUE THREAD

**Issue by javiavid** [Quorafind/Obsidian-Memos#19]
Sometimes when I double click on an entry already created and I try to modify it I get this error and sometimes it has erased the entry.
The plugin remains a bit unstable and no longer works well, the solution is to close obsidian and open it.

**Comment by Quorafind** [comment]
it is werid, next time when you find this issue, you could use CTRL+ALT+I to open console and then screenshot the error to me ?

**Comment by javiavid** [comment]
Ok, next time I'll send it to you.

**Comment by javiavid** [comment]
This is what happens, I think it always happens when I double click on a post already created.
In this case I haven't lost the entry, but it won't let me delete them. The empty post was not created by me.

https://user-images.githubusercontent.com/7627504/148944479-c4291498-1d39-4f52-bd5c-e7ba4246bfe7.mp4

This is the inside of the .md file.
![image](https://user-images.githubusercontent.com/7627504/148944574-a3ef4a76-2166-4644-9a9f-97557b14ba53.png)

And this is the screenshot of the console.
The .md file is from the 11th, not the 10th as it says in the screenshot, so maybe it's not the same.
There was nothing else on the console at this time.

![image](https://user-images.githubusercontent.com/7627504/148942659-ef570c89-faf7-4bed-b0eb-27e6f0378733.png)

**Comment by javiavid** [comment]
I've deleted from notepad++ the empty post and clicked on MEMOS to update.
The empty post does not appear, but the plugin is unstable.
I send you a screenshot of new messages in the console before closing obsidian.

![image](https://user-images.githubusercontent.com/7627504/148945613-bcbd3ff8-8b4b-46c3-9353-64056f91a916.png)

**Comment by Quorafind** [comment]
Thanks for so many details!!!

**Comment by javiavid** [comment]
I have tried version 1.1.10 and I think it happens less. It is still happening but it is less common, maybe it happens when a new daily note is created. I'll try a few days to see if I can reproduce exactly the steps for the error.

**Comment by hqweay** [comment]
> I have tried version 1.1.10 and I think it happens less. It is still happening but it is less common, **_maybe it happens when a new daily note is created._** I'll try a few days to see if I can reproduce exactly the steps for the error.

I think so. It occurs to me when I install the plugin and try to delete a memo, when I restarted the plugin, it works great now.

**Comment by Quorafind** [comment]
Fixed in #55 

When you create a new daily note, cannot find the new dailynote because forget to refresh the storage
