### ISSUE TITLE
点击分享无反应

### ISSUE THREAD

**Issue by biorz** [Quorafind/Obsidian-Memos#197]
点击分享时报错

![截屏2022-04-24 09 50 46](https://user-images.githubusercontent.com/15077010/164952357-6f6ea9e7-0dc2-4039-a599-23ed43953754.png)

**Comment by uangunai** [comment]
我这边分享也是没任何反应。难不成是图片放的路径和指向的路径设置有问题？

**Comment by MingchaoShi** [comment]
今天从1.8.x升级到了1.9.5，也发现点击分享毫无反应，但我升级前的版本是正常的，确认了背景图路径和名称没有问题。

**Comment by juestchaos** [comment]
@biorz @MingchaoShi 
感谢对 memos 关注 ，在 memos 2.x 系列中已经无法复现对应问题
[Thino 用户使用指南]( https://pkmer.cn/show/20231109234455 )
