### ISSUE TITLE
Plugin hijacks the CSS

### ISSUE THREAD

**Issue by insecurejezza** [Quorafind/Obsidian-Memos#2]
Love this plugin already. I am having issues with the plugin hijacking elements of my CSS like font and font colour. Would be great to be able to retain my own CSS. 

Buying you a coffee though. Big Calendar and this are some of the most exciting plugins to have come out in a number of months.

**Comment by Quorafind** [comment]
Yep, will be fixed soon, sorry!

**Comment by Quorafind** [comment]
Fixed in #4
