### ISSUE TITLE
能不能有给缓存，然后后台慢慢更新

### ISSUE THREAD

**Issue by jaycamu** [Quorafind/Obsidian-Memos#200]
条目很多的时候，每次启动都要花一些时间才能刷出来，如果条目持续增多，这个等待时间体验就比较差了，手机端

**Comment by Quorafind** [comment]
难度有点大，我考虑一下要怎么实现

**Comment by xpmax2022** [comment]
按文件名（日期）倒序搜索，满足一定条数条就显示，后台再往前搜索叠加，不知道可行不😀

**Comment by juestchaos** [comment]
@jaycamu 
@Yubuxin 
感谢关注，memos 2.x 开始支持懒加载，及其他性能提升。
[Thino 用户使用指南]( https://pkmer.cn/show/20231109234455 )
