### ISSUE TITLE
汇总无标签的memo

### ISSUE THREAD

**Issue by zhxrrb** [Quorafind/Obsidian-Memos#202]
由于有的在输入的时候并没有加入标签，之后想再加标签的话就得在日记或者全部的memo中挨个儿去找，能不能给所有没有加标签的memo汇总到一个分类下？这样方便后续快速查找和修改

**Comment by Quorafind** [comment]
![image](https://user-images.githubusercontent.com/13215013/165008762-7a9eed7d-04ff-4c39-a5bf-6db4445ef882.png)

点击这里就行

**Comment by zhxrrb** [comment]
原来是我自己没搞懂，谢谢bon~q(≧▽≦q)
