### ISSUE TITLE
Memos中链接失效

### ISSUE THREAD

**Issue by KeisonChem** [Quorafind/Obsidian-Memos#208]
![8GIEF8(FXV27(G {QEFAXGL](https://user-images.githubusercontent.com/101973058/166139060-8d6156a4-1929-400d-9b96-b21857d7bfd9.png)
如图，memos中用[[]]关联的文章，更改存放的文件夹后，打开时无法显示，右上角提示folder already exists

**Comment by KeisonChem** [comment]
上次存在问题的版本是1.9.5，最新的1.9.6没有修复该问题

**Comment by juestchaos** [comment]
@KeisonChem 
感谢关注 memos，2.x 版本中已经修复了此问题，已经生成 [[文件A]] 当文件名修改为B时，对应卡片会变化
