### ISSUE TITLE
Bug: ipad端插件的memos 条目显示有问题

### ISSUE THREAD

**Issue by vagrant-psyche** [Quorafind/Obsidian-Memos#210]
win10端和安卓端的条目显示正常，但是唯独ipad端的条目显示有问题，所有条目挤压在了一起，且和编辑区重叠

win10：
![win10](https://user-images.githubusercontent.com/37809377/166638539-c8f31b53-59af-458b-9383-b7bd1935e448.png)

安卓:
![1651648437408](https://user-images.githubusercontent.com/37809377/166638547-c88e9c27-f77d-4ae2-8d93-62526e949e41.jpg)

ipad:
![IMG_0137](https://user-images.githubusercontent.com/37809377/166638518-70437b72-6eb1-412d-8783-e32e87966ef4.PNG)

想知道这是什么原因造成的，方便修正吗？

**Comment by Quorafind** [comment]
和 iOS 版本有关，我手头上没有低版本的设备，建议升级系统

**Comment by vagrant-psyche** [comment]
好的，谢谢
