### ISSUE TITLE
Bug:  After update to1.9.5, fail to create new Memos

### ISSUE THREAD

**Issue by charles-sun0v0** [Quorafind/Obsidian-Memos#211]
更新后出现，在新的一天，新建 memos 的时候，报错

```
periodicNotes:createPeriodNotes is not a function
```
Btw, 我用 Periodic Notes 创建 Daily Note  

Workaround: 手动创建 Daily Note, 就可以继续输入了

**Comment by vagrant-psyche** [comment]
我也遇到了这个错误

**Comment by Quorafind** [comment]
更新试一下

**Comment by charles-sun0v0** [comment]
更新到1.9.6 还是一样的，对应的Periodic Note 版本是0.0.17

**Comment by charles-sun0v0** [comment]
It is solved in #223 and released in 1.9.7.  Well done, thanks. I'll close the issue.

**Comment by bagameow** [comment]
Looks like 1.9.7 still doesn't work.  Same message.
Periodic note is 0.0.17.

**Comment by wwyf** [comment]
obsidian : 1.0.3
periodic note: 0.0.17
Memos : 1.9.7

<img width="262" alt="image" src="https://user-images.githubusercontent.com/23121291/198482604-9968e02b-faf3-42a7-851f-2c171076f2bd.png">
