### ISSUE TITLE
请问常用标签的计数字体颜色怎么修改呢？

### ISSUE THREAD

**Issue by zdway10** [Quorafind/Obsidian-Memos#215]
请问常用标签的计数字体颜色在哪里修改？用了深色主题，基本看不清，谢谢。
<img width="148" alt="1" src="https://user-images.githubusercontent.com/38562346/167536529-c4da2b4f-de76-4549-b9e3-7c8a62ef27a1.png">

**Comment by juestchaos** [comment]
你可以使用
.tag-item-container .tag-count 选择器来实现
感谢对 memos 关注，也可以关注 memos 2.x 
[Thino 用户使用指南]( https://pkmer.cn/show/20231109234455 )
