### ISSUE TITLE
界面排版问题（Bug？）

### ISSUE THREAD

**Issue by wuzhen97** [Quorafind/Obsidian-Memos#222]
非常感谢作者能够提供这么美观实用的工具。目前我第一次安装Memos（Windows10），启动后发现排版和大家不一样，希望能够帮助我解决这个问题：

![1653190666(1)](https://user-images.githubusercontent.com/61906420/169677524-bb016096-f81a-42b3-ab3e-e53a9583a411.jpg)

**Comment by hqweay** [comment]
换回默认主题；关闭 CSS 代码片段；这类操作后再看看呢？

**Comment by wuzhen97** [comment]
> 换回默认主题；关闭 CSS 代码片段；这类操作后再看看呢？

十分感谢您的回答！换回默认主题后，问题确实解决了，但是我非常喜欢目前的主题，您认为哪些操作可以解决这个问题呢。

注：我通过 “Yin and Yang theme” 搭配 “style setting ” 插件定制化自己的风格。

**Comment by 1wingedangel** [comment]
Willemstad 主题也有类似的现象，供参考。

**Comment by wuzhen97** [comment]
> flex-wrap: nowrap;

感谢！！！！已经解决了
