### ISSUE TITLE
更新Obsidian15.6之后memos页面没法关闭

### ISSUE THREAD

**Issue by Yubuxin** [Quorafind/Obsidian-Memos#240]
如题。
Obsidian版本号为15.6，打开memos界面后，再跳转其他页面（无论是在文件列表点击还是用快捷键跳转）就会在memos界面旁打开第二个窗口，memos界面只能通过右上角的关闭键来关闭。

**Comment by Quorafind** [comment]
试一下kanban等诸如此类的单独页面插件看是否是一样的表现

**Comment by gavinwoo007** [comment]
准确的说是开启Sliding Panes全局模式后，打开Memos界面会打开一个空白页，需要移动下面的scrollbar才能回到Memos页面。其他插件目前没发现这个问题。

**Comment by Yubuxin** [comment]
> 

kanban也出现了一些跟sliding pane有关问题，但并没有出现无法关闭的情况。此外，同为单独页面的db-folder也未出现这种情况。

**Comment by Yubuxin** [comment]
@Quorafind kanban也出现了一些跟sliding pane有关问题，但并没有出现无法关闭的情况。此外，同为单独页面的db-folder也未出现这种情况。

**Comment by lefinite** [comment]
遇到了相同的问题。
在打开一个文件的情况下点击memo
<img width="1299" alt="iShot_2022-08-11_14 27 57" src="https://user-images.githubusercontent.com/23370734/184076042-d7e8a9f2-47e5-47d7-96ea-b99736052024.png">
就会变成如下图所示，memo在新窗口打开，已经打开的文件窗口变成一个无文件窗口，且无法关闭。
<img width="1299" alt="iShot_2022-08-11_14 28 13" src="https://user-images.githubusercontent.com/23370734/184076117-1ad0a57d-7ca1-4962-b341-e78ecb05a615.png">

**Comment by mathisgauthey** [comment]
Same problem here. Hope there'll be a fix soon o/

**Comment by zthxxx** [comment]
Have same problem.  
> Obsidian version: v0.15.9
> Obsidian Memos v1.9.7

**Comment by juestchaos** [comment]
@Yubuxin 
感谢关注memos ，你提交的问题，在最新的2.x 未复现
[Thino 用户使用指南]( https://pkmer.cn/show/20231109234455 )
