### ISSUE TITLE
有没有办法新窗口打开

### ISSUE THREAD

**Issue by eightHundreds** [Quorafind/Obsidian-Memos#241]
新版ob支持移动到新窗口.
希望能有一个命令快速地在新窗口中打开memo(并always on top), 然后用户可以把这个命令设置为全局快捷键

**Comment by MingchaoShi** [comment]
现在在新窗口打开Memos后，第一个输入#，会导致页面空白。

**Comment by cumany** [comment]
> 现在在新窗口打开Memos后，第一个输入#，会导致页面空白。

这行代码注释了就解决了
https://github.com/Quorafind/Obsidian-Memos/blob/858fba6cd16bc2e7e326279225f7a55b35be8a94/main.js#L13098

**Comment by cumany** [comment]
> 新版ob支持移动到新窗口. 希望能有一个命令快速地在新窗口中打开memo(并always on top), 然后用户可以把这个命令设置为全局快捷键

用quickadd 宏就可以实现。

**Comment by MingchaoShi** [comment]
> > 现在在新窗口打开Memos后，第一个输入#，会导致页面空白。
> 
> 这行代码注释了就解决了
> 
> https://github.com/Quorafind/Obsidian-Memos/blob/858fba6cd16bc2e7e326279225f7a55b35be8a94/main.js#L13098

不会空白了，但有副作用，输入#号后无法从标签列表中选择了。

**Comment by cumany** [comment]
我这里没有问题 可以正常使用

**Comment by juestchaos** [comment]
@eightHundreds 
@MingchaoShi 
感谢关注 memos，反馈的问题已经在 memos 2.x 版本开始完成
效果如下

![image](https://github.com/Quorafind/Obsidian-Memos/assets/241007/5865ff9c-947d-4e95-8a21-b7058cedcaec)
