### ISSUE TITLE
在性能较弱的电脑上打开已出现明显卡顿

### ISSUE THREAD

**Issue by Yubuxin** [Quorafind/Obsidian-Memos#252]
目前积攒了五百多条 memo，总计大概七八万字。在公司性能比较弱的台式机上打开 Memos 界面、编辑和创建新 memo 时，都有 2—3 秒的卡顿，动画也会出现掉帧现象，很影响使用体验。

Memos 似乎没有使用懒加载策略，每次打开都是一次加载完毕全部内容，这样的问题是，memo 这种东西肯定是经常要用的，时间长了积攒几千条都有可能，拿设备性能来硬解感觉不是长久之法。

**Comment by hellspector** [comment]
配置很好的电脑也是，手机上也是。我也是有500多条memos了，每次打开都卡，已经严重影响到使用体验了。唉。

**Comment by Quorafind** [comment]
缓存策略还在思考，九月份会开始解决这半年来的 issues...

**Comment by Yubuxin** [comment]
@Quorafind 辛苦了！
希望 Memos 能够越来越好，目前已是我在 Obsidian 里最离不开的插件之一了。

**Comment by hellspector** [comment]
> 缓存策略还在思考，九月份会开始解决这半年来的 issues...

期待，现在最期望的就是：
1. 搜索的不规则匹配 ——让搜索更加简单
2. 智能加载——让打开变得迅速

**Comment by hellspector** [comment]
又经过1个月的使用，已经到600多条了。卡到不能自理。郁闷呀。
