### ISSUE TITLE
Support customizing item prefix

### ISSUE THREAD

**Issue by wenlzhang** [Quorafind/Obsidian-Memos#26]
Since Memos currently supports identifying the following item formats, it would be great if one can customize the default item format when adding new items.
```
- 19:00 in daily note.
- [ ] 19:00 in daily note.
```
The current default new item format is `- 19:00 in daily note.` It would be great if one can change the default item prefix to be `- [ ] ` such that all new items would be tasks. One may change this in the configuration pane of this plugin.

Also, since Big Calendar supports the following three item formats, it would be great if Memos can also support the first format.
```
- [ ] in daily note.
- 19:00 in daily note.
- [ ] 19:00 in daily note.
```
Specifically, when showing items of the first format in Memos interface, i.e. `- [ ] in daily note.`, the default time can be set to `00:00`.

**Comment by Quorafind** [comment]
This feature will be added when big calendar get an update, because both of these plugins need customizing

**Comment by Quorafind** [comment]
Check #43
