### ISSUE TITLE
Command-W does not close the Memos pane

### ISSUE THREAD

**Issue by crucialfelix** [Quorafind/Obsidian-Memos#261]
Hello,

Most windows can be closed with (mac) Command-W. I guess the Memos pane captures the key stroke.

If you can't avoid capturing the key stroke, maybe you could add a command "Obsidian Memos: Close pane" 

Thank you for publishing such a great plugin!

**Comment by Quorafind** [comment]
I will test this on my mac

**Comment by crucialfelix** [comment]
It works now. Either you fixed and updated it or the new Obsidian has resulted in it working now.  I can command-w to close the memo pane.

Thank you again for the plugin!
