### ISSUE TITLE
[BugReport]天数计算逻辑有误

### ISSUE THREAD

**Issue by frankcbliu** [Quorafind/Obsidian-Memos#271]
![image](https://user-images.githubusercontent.com/36353894/198284843-5358e807-80f2-4dbb-955c-f96e114cdee1.png)
如上图所示，只写了一条memo，天数却显示的2天

**Comment by Quorafind** [comment]
请问您所在的位置是？此外，您的 Memos 版本是多少？

**Comment by frankcbliu** [comment]
> 请问您所在的位置是？此外，您的 Memos 版本是多少？

@Quorafind 位置是深圳。最新版 1.9.7，在插件商店直接下载安装的
![image](https://user-images.githubusercontent.com/36353894/198497832-91aa171f-b7c5-4aef-ac44-7409f80b08b2.png)

**Comment by camellia-free** [comment]
我也遇到了类似的情况

**Comment by cxyfreedom** [comment]
有同样的问题

**Comment by juestchaos** [comment]
@frankcbliu @camellia-free @cxyfreedom 
感谢对 memos 关注，各位反馈的问题，已经无法在 2.x 版本系列中复现
[Thino 用户使用指南]( https://pkmer.cn/show/20231109234455 )
