### ISSUE TITLE
图片为外链(如图床)，非本地图片时，点击分享无法显示该图片

### ISSUE THREAD

**Issue by huangduzhang** [Quorafind/Obsidian-Memos#284]
### Bug Description

rt，感觉像是生成分享图片时，异步问题导致。

### Obsidian Version

1.9.7

### Which editor are you using?

- [ ] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by juestchaos** [comment]
此问题2.0已经修复，请期待

**Comment by juestchaos** [comment]
已经修复了
