### ISSUE TITLE
[Bug]: 不兼容 obsidian-periodic-notes 0.0.17

### ISSUE THREAD

**Issue by bytemain** [Quorafind/Obsidian-Memos#292]
### Bug Description

设置项中改成使用 periodic-notes，然后会报错没有该函数

### Relevant Screenshot

<img width="303" alt="CleanShot 2022-12-11 at 22 02 08@2x" src="https://user-images.githubusercontent.com/13938334/206908188-0419ceb7-6563-4d43-b7f7-601ac744e9f8.png">

### Obsidian Version

1.9.7

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by bytemain** [comment]
https://github.com/Quorafind/Obsidian-Memos/commit/f8855bb70f138c04f8df003aa926875d08924191#diff-94e01b9bcaf37dddbea5defec6f62b685b2f2362d74b42d01d29fab89a70432b

看起来是这个修改的问题：
<img width="1196" alt="CleanShot 2022-12-11 at 22 08 41@2x" src="https://user-images.githubusercontent.com/13938334/206908529-348bb720-57cf-4227-a877-d9f5dc7436c8.png">


可以通过判断一下有没有想要的函数来暂时兼容多种创建。

**Comment by bytemain** [comment]
link https://github.com/Quorafind/Obsidian-Memos/issues/211

**Comment by bytemain** [comment]
我自己尝试了下，很难完全兼容

**Comment by Garphy** [comment]
设置改回日记插件能正常发布，看起来也不影响periodic-notes的正常使用.
