### ISSUE TITLE
Support hiding completed task items

### ISSUE THREAD

**Issue by wenlzhang** [Quorafind/Obsidian-Memos#31]
Currently, items of the format `- [x] 19:00 in daily note.` would show in the plugin interface and be counted in the heat map. However, such items may have been completed/processed. Therefore, it would be great if there can be an option in the configuration pane to choose whether to show such items.

Alternatively, there can be an option to create a filter/query to filter out such checked items.

**Comment by Quorafind** [comment]
Supported in #61
