### ISSUE TITLE
Feature Request: 关于新手引导。

### ISSUE THREAD

**Issue by BelugaRex** [Quorafind/Obsidian-Memos#321]
### Feature Requested

感觉可以设立一个wiki，用github自带的功能就可以了，写点入门设置的东西，这个插件现在还算不上是开箱即用，还是需要再稍微小小折腾的。
例如想要用非官方的日记格式的话，memos可能会读取不到，而且设置的日记默认保存文件夹位置也可能导致读取失败，所以本身这款插件应该连带同时下载dataview，类似这种比较细枝末节的东西还是有点影响使用体验的。

### Checklist

- [x] The feature would be useful to more users than just me.

**Comment by juestchaos** [comment]
感谢关注 memos
memos 已经接收到反馈，并在 2.x 开始建立了用户指南
[Thino 用户使用指南]( https://pkmer.cn/show/20231109234455 )
