### ISSUE TITLE
Feature Request: 希望能修改下代码块在暗黑模式下的显示

### ISSUE THREAD

**Issue by NeonBubbles** [Quorafind/Obsidian-Memos#338]
### Feature Requested

当使用obsidian的dark模式时，memos中的代码块依然是白色，不仅有些刺眼而且看不清楚里面的内容。希望有空能修改下暗黑模式下的颜色。
谢谢！

### Relevant Screenshot

![image](https://github.com/Quorafind/Obsidian-Memos/assets/43613294/932de793-1642-48f5-961b-bee7ff09e316)

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by NeonBubbles** [comment]
还有热力图的颜色希望也能顺便修改一下

**Comment by hellspector** [comment]
> 还有热力图的颜色希望也能顺便修改一下

作者不会再改了，你都没叫他嘴脸，恶心的一逼。人前一套，人后一套。

**Comment by juestchaos** [comment]
@NeonBubbles 
感谢对 memos 关注，已经在 2.x 中修复了此问题，效果如下

![image](https://github.com/Quorafind/Obsidian-Memos/assets/241007/49db67ef-0c6b-4293-8576-843e1fb4eac7)
