### ISSUE TITLE
请问能支持二级标题吗？

### ISSUE THREAD

**Issue by lin0kin** [Quorafind/Obsidian-Memos#35]
我的日记里有一级标题和二级标题， 我只想展示二级标题 `## memo` 里的内容，现在会展示所有的标签下的内容， 请问可以支持一下吗？

另外方便的话，能增加自定义时间标签格式吗？我的时间都是 `[time] ::  `这样的，谢谢

**Comment by Quorafind** [comment]
自定义标题在设置中将 `# Journal` 修改为你需要的二级标题即可，有一个 Head 的设置项 ，例如你的是 `## memo`

自定义时间格式下周的版本中会更新

**Comment by Quorafind** [comment]
需要修正一下，就是你只需要输入`# memo` 就可以到这个标题下，不需要 ##

**Comment by lin0kin** [comment]
> 需要修正一下，就是你只需要输入`# memo` 就可以到这个标题下，不需要 ##

 请问可以只展示 `# memo` 中的内容吗? 现在连 `# talk` 中的内容也会展示出来

**Comment by Quorafind** [comment]
目前还没有限标题块范围的功能

**Comment by Quorafind** [comment]
#37 有人实现了标题块范围内的 memo 的识别，等我看一下没问题下个版本就支持了

**Comment by lin0kin** [comment]
> #37 有人实现了标题块范围内的 memo 的识别，等我看一下没问题下个版本就支持了

太棒了,谢谢
