### ISSUE TITLE
[Bug]: Memos获取失败

### ISSUE THREAD

**Issue by nidongpinyinme** [Quorafind/Obsidian-Memos#354]
### Bug Description

之前正常用过一段时间，记不清什么时候突然不好用了，具体表现为只能记住本次obsidian开启时通过Memos插件记录的memos，对于文件中进行的更改获取不到更新，重启obsidian后获取不到旧Memos。
控制台未报错。

### Relevant Screenshot

<img width="176" alt="image" src="https://github.com/Quorafind/Obsidian-Memos/assets/35392985/26fddc3f-39e5-461b-9ee1-32eb22b91b77">
<img width="235" alt="image" src="https://github.com/Quorafind/Obsidian-Memos/assets/35392985/7096b294-7bc3-4f69-b9cd-7bc3fe708007">

### To Reproduce

暂未确认如何复现，因为发生问题后一直没正常过。

### Obsidian Version

1.4.16

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
有可能是你的日记插件的设置或者你的日记模板发生了变化；你可以去 Memos 的获取目标标题下的内容清空对应的内容，这样能够获取全文的 Memos

**Comment by nidongpinyinme** [comment]
@Quorafind 感谢回复，但是当前已经设置为空了。
同时测试了给出标题，并在文件顶部添加相应标题，测试的Memos依旧插入到了文末，似乎插件没有读取到文件内容。
请问还有什么排查思路吗？

**Comment by Quorafind** [comment]
可以看下是不是日记文件夹的路径发生了变化

**Comment by nidongpinyinme** [comment]
@Quorafind 都是没变过的啊，跟放在iCloud上有关系吗，但是之前也是放在iCloud上的

**Comment by nidongpinyinme** [comment]
跟iCloud没关系，复制到了本地也是不能用的，但是我在沙箱里新拉的插件使用正常。把第三方插件都关闭测试也是不能用的。请问还有别的测试思路吗。

**Comment by nidongpinyinme** [comment]
不好意思，定位到问题了，是我的一个日记文件乱码导致的 :(
