### ISSUE TITLE
请问一下这些地方该如何修改？

### ISSUE THREAD

**Issue by Mollyoyo** [Quorafind/Obsidian-Memos#36]
我不是程序员，不会看代码，试着改了css里的几个色值，完全没反应呀。

我也不知道为什么，我的界面发黄很严重。
![image](https://user-images.githubusercontent.com/30024196/149582318-a792949c-9126-4b5a-b59a-9d66aabaacf3.png)

**Comment by Mollyoyo** [comment]
画圆圈的几个地方是我想改的。。。
希望作者可以说下，到底是改哪几个地方。

感谢啦

**Comment by Quorafind** [comment]
😂 不好意思现在才回复你，这些地方的颜色你是希望改成什么样子的呢，我可以看看是否能让这个颜色对比好看点。

**Comment by Quorafind** [comment]
如果您这边对新的 Memos 有外观上的建议您可以重开这个 issue 或者另外开一个新的 issue 😉
