### ISSUE TITLE
[Bug][Thino]: 关于 Image Captions 在 Thino 下的两种模式下的迥异效果的探讨

### ISSUE THREAD

**Issue by alexinea** [Quorafind/Obsidian-Memos#361]
### Bug Description

不得不说，既然是 Image Captions 表现异常，那么首先你得有张图。

开发组截图说未能复现，但……你没有一个 Image 在里面，如何复现呢……况且，Image Captions 的功能较为单一，不需要猜。这点需要批评。

以下是说明：

形如：
```
![[YourImageName|Caption]]
```

的结构，应当在图片下方呈现标题“Caption”
- 当 Thino 位 Center 时，能呈现标题（但未能正确使用 CSS）
- 当 Thino 位独立窗体时，标题不能呈现，Image Captions 插件未能起作用（表现为未能写 HTML）

相关插件：
- obsidian://show-plugin?id=image-captions

不能确定这是否是 BUG 还是 by design，故标题缀“探讨”

### Relevant Screenshot

![image](https://github.com/Quorafind/Obsidian-Memos/assets/980129/46e9df6f-b5e0-4b78-9da1-e72111b471f5)
位 Center 效果（呈现，但 CSS 出现问题）

![image](https://github.com/Quorafind/Obsidian-Memos/assets/980129/1f6ababa-0a77-4eae-b977-78e25f3a19f1)
位独立窗体，标题未能呈现

### To Reproduce

无

### Obsidian Version

1.4.16

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by juestchaos** [comment]
![image](https://github.com/Quorafind/Obsidian-Memos/assets/241007/f290c855-b102-4d6f-b8d9-6192a5c7d2bb)

**Comment by alexinea** [comment]
1.4.16 和后续版本的差异么？我们一起来确定一下问题所在。

**Comment by alexinea** [comment]
![image](https://github.com/Quorafind/Obsidian-Memos/assets/980129/eddd63f8-7e0f-438a-8e9c-12434da9281c)
在独立窗体下的 HTML

Center、Left、Right 模式下都是正常表现。

**Comment by alexinea** [comment]
根据 bon 佬的结论，这可能是第三方插件的问题，赞美 bon 佬，他还排查出第三方插件到底哪里出了问题。

这个问题不是 Thino 的，以上。
