### ISSUE TITLE
[Bug][Thino]: 与核心插件工作区不兼容

### ISSUE THREAD

**Issue by windily-cloud** [Quorafind/Obsidian-Memos#365]
### Bug Description

当加载任意包含thino 的工作区时，thino 将无法点击 note it 按钮。怀疑是加载时把啥给卸了

### Relevant Screenshot

![图片](https://github.com/Quorafind/Obsidian-Memos/assets/30640638/9ec3a12b-914c-471c-82a0-502ceec821e2)

### To Reproduce

1. 打开thino
2. 用命令行创建一个工作区
3. 加载此工作区
4. 此时输入thino，note it按钮无法使用

### Obsidian Version

1.4.16

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by juestchaos** [comment]
以收入到内部讨论
