### ISSUE TITLE
[Bug][Thino]: UI错位

### ISSUE THREAD

**Issue by windily-cloud** [Quorafind/Obsidian-Memos#370]
### Bug Description

UI错位

### Relevant Screenshot

![c80b48ac5d57ea1d22b1d8b54a6772a](https://github.com/Quorafind/Obsidian-Memos/assets/30640638/8b8de926-89d3-4948-a6c3-fab076d781f0)

### To Reproduce

打开thino ，页面正常。然后打开随便另外一篇笔记，此时页面在另外一篇笔记中。退出ob。打开ob ，此时页面是刚才另一篇笔记，切换到thino ，就会出现这个问题。

### Obsidian Version

1.4.16

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by juestchaos** [comment]
已经收入到内部讨论

**Comment by juestchaos** [comment]
已经修复了2.2.x 未复现

**Comment by windily-cloud** [comment]
已在2.2.3修复
