### ISSUE TITLE
[Bug][Thino]: 调整窗口大小后，段内换行渲染不正确

### ISSUE THREAD

**Issue by Ami-Nous** [Quorafind/Obsidian-Memos#374]
### Bug Description

笔记中带有段内换行时，obsidian 窗口宽度调整到 thino 左侧栏隐藏之后，换行边距突然变大。

测试用的是结尾加两个空格的段内换行。关闭obsidian的严格换行模式后，不加空格的段内换行也能复现此bug

### Relevant Screenshot

窗口宽度调小到左侧栏隐藏之后，段内换行的行距会显示成比段落间行距还大：

![image](https://github.com/Quorafind/Obsidian-Memos/assets/155599779/d67cb3ab-75d0-484b-b499-eecf99c516ec)

窗口宽度调整到左侧栏显示之后，显示是正常的：

![image](https://github.com/Quorafind/Obsidian-Memos/assets/155599779/937cf73e-9db6-4448-9140-c83ac6fdfa7d)

### To Reproduce

1. 新建笔记，输入以下文字，发送
```
test 1

test 2  
test 3
```
3. 缩小 obsidian 窗口宽度，直到 thino 左侧栏隐藏

### Obsidian Version

1.5.3

### Which editor are you using?

- [x] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Ami-Nous** [comment]
2.2.0版本问题依旧

**Comment by juestchaos** [comment]
测试已经修复，提供相关问题细节

**Comment by Ami-Nous** [comment]
重新测试发现，浅色模式下已经修复，深色模式下问题依旧

**Comment by juestchaos** [comment]
抱歉我还是无法复现，或许你可以给我 主题，或者 其他 snpippets 信息

**Comment by Ami-Nous** [comment]
[test.zip](https://github.com/Quorafind/Obsidian-Memos/files/14078729/test.zip)
![image](https://github.com/Quorafind/Obsidian-Memos/assets/155599779/4ae1f641-43bf-40ef-9853-d09104bcb5a9)
![image](https://github.com/Quorafind/Obsidian-Memos/assets/155599779/9d63390a-4186-4249-8779-0c512805e003)

**Comment by juestchaos** [comment]
未能复现

缩小宽度
![image](https://github.com/Quorafind/Obsidian-Memos/assets/241007/c89055d9-cc4d-4d8e-b2ba-33633f377f20)

放到侧边栏
![image](https://github.com/Quorafind/Obsidian-Memos/assets/241007/ee69d0c0-6771-4f51-9afa-c4ce990ff738)

**Comment by Ami-Nous** [comment]
2.2.2版本测试，深色模式依然存在问题

**Comment by windily-cloud** [comment]
https://github.com/Quorafind/Obsidian-Memos/assets/30640638/cb6f4bbf-cb50-40c0-a75f-e887be4501b9

**Comment by juestchaos** [comment]
2.2.3 已经修复
