### ISSUE TITLE
[Bug]: 电脑版输入法输入时点esc直接退出

### ISSUE THREAD

**Issue by fearlessbar** [Quorafind/Obsidian-Memos#376]
### Bug Description

obsidian Version 1.5.3
插件1.9.7
如录屏所示：

https://github.com/Quorafind/Obsidian-Memos/assets/8664569/5eb46e7c-6afd-4979-9f32-f4ed22a3bdab

### Obsidian Version

1.9.7

### Which editor are you using?

- [ ] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by juestchaos** [comment]
不知道你使用的输入法？
另外，我在  memos 2.x 上并未复现此问题

**Comment by fearlessbar** [comment]
> 不知道你使用的输入法？
> 
> 另外，我在  memos 2.x 上并未复现此问题

搜狗输入法

**Comment by juestchaos** [comment]
我没有在 2.x 上复现这个bu
我复现步骤是这样的
1、安装搜狗输入法
2、在 thino 的编辑框中输入 内容，并在未分选定候选项的情况下，尝试按住退格或esc 。都表现正常

**Comment by juestchaos** [comment]
测试了 1.x 版本也没有这个 esc 的问题，请提供更多信息
