### ISSUE TITLE
[Bug][Thino]: 日记中相同时间的笔记显示顺序不正确

### ISSUE THREAD

**Issue by Ami-Nous** [Quorafind/Obsidian-Memos#380]
### Bug Description

手动编辑日记文件后，存在相同时间的笔记项时，界面显示顺序不正确

### Relevant Screenshot

![image](https://github.com/Quorafind/Obsidian-Memos/assets/155599779/43cb14d7-f26a-46f1-a9bb-14943650d347)

### To Reproduce

编辑日记文件，插入以下内容
```
- 09:25 test1
- 09:25 test2
- 09:25 test3
- 09:26 test4
```

### Obsidian Version

1.5.3

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by juestchaos** [comment]
哪里有问题？可以提供细节吗？
我试了你留下的文本内容，是按照时间倒序排列的

![image](https://github.com/Quorafind/Obsidian-Memos/assets/241007/b092f01c-5aba-4872-a4b2-5825ee4eceb6)

**Comment by Ami-Nous** [comment]
test1, test2, test3是同一个时间的。复制我给的测试用例就可以了

**Comment by Ami-Nous** [comment]
> 哪里有问题？可以提供细节吗？ 我试了你留下的文本内容，是按照时间倒序排列的
> 
> ![image](https://private-user-images.githubusercontent.com/241007/295100103-b092f01c-5aba-4872-a4b2-5825ee4eceb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3ODI0NDgsIm5iZiI6MTcwNDc4MjE0OCwicGF0aCI6Ii8yNDEwMDcvMjk1MTAwMTAzLWIwOTJmMDFjLTVhYmEtNDg3Mi1hNGIyLTU4MjVlZTRlY2ViNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQwNjM1NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yM2YzYzQ5OGY4YWUwMzk4ZTA0M2ZkOTgwNTIyMWJmMjFiNjQwYWY5ZTk1MjY5MDQ4YmQ4MDI3Yjk2ZDllOTcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SyfNFpu4CCVYDarFQEyTYc3Y07eZjltqYBge3FqYG1I)

你测试的都是不同时间了，所以顺序是对的

**Comment by juestchaos** [comment]
2.2.3 已经释放，参看 thino 更新日志 
[Thino 2.X （原名 Obsidian memos）更新记录]( https://pkmer.cn/show/20230913172534 )
