### ISSUE TITLE
[Bug]: 界面语言切换为其他语言如英语后，之前写过的所有条目都不能显示，且无法添加新日记

### ISSUE THREAD

**Issue by FeiLZX3Km** [Quorafind/Obsidian-Memos#384]
### Bug Description

界面语言切换为其他语言如英语后，之前写过的所有条目都不能显示，且无法添加新日记。

### Obsidian Version

1.9.7

### Which editor are you using?

- [ ] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by juestchaos** [comment]
在 1.x 和 2.x 版本上都没有复现这个现象

**Comment by FeiLZX3Km** [comment]
> 在 1.x 和 2.x 版本上都没有复现这个现象


https://github.com/Quorafind/Obsidian-Memos/assets/21981195/0d51b312-e0c7-4523-ac5f-09a9944b3700

**Comment by FeiLZX3Km** [comment]
> 没有复现出来 这是切换到中文的数据截图 ![image](https://private-user-images.githubusercontent.com/241007/297685707-23694569-e0b9-4462-8e02-7bca4a76f9f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1Njk1OTQsIm5iZiI6MTcwNTU2OTI5NCwicGF0aCI6Ii8yNDEwMDcvMjk3Njg1NzA3LTIzNjk0NTY5LWUwYjktNDQ2Mi04ZTAyLTdiY2E0YTc2ZjlmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQwOTE0NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NDZkYzRmMmM1MTdhOGExNDNlMGQzYzBmN2M5YjkzNTg2MmI5ZTExNzE2YTcyZTliZmNhMDIzNTFhNTliMWUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WbiQ7j19UrLQ2xya7jnqUEvVKFDuPDs1IM5cCmigkgQ) 这是切换到英文的数据截图 ![image](https://private-user-images.githubusercontent.com/241007/297685878-480265fa-9798-48f2-a487-29820a0778c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1Njk1OTQsIm5iZiI6MTcwNTU2OTI5NCwicGF0aCI6Ii8yNDEwMDcvMjk3Njg1ODc4LTQ4MDI2NWZhLTk3OTgtNDhmMi1hNDg3LTI5ODIwYTA3NzhjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQwOTE0NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjE4NGIxNzk2M2M3NDNjOTM0ZmJlODYyMTQzY2RlNDMwYTgyYzg5ODA3NTY2OWY2OTE1NWQzMmE1N2ZhOTkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Z4k6ULK4djEbBXbnK-HUnhzsb1eDlvelWkP5xUCW9RE)

好吧……
