### ISSUE TITLE
Feature Request: 能否单独保存到一个文件夹，而不是跟日记文件混用

### ISSUE THREAD

**Issue by ccdyd** [Quorafind/Obsidian-Memos#387]
### Feature Requested

现在保存出来的文字是跟日记混用，在当天的日记下面出现，这样后续整理会乱，希望能跟日记分开，单独保存到一个文件夹下面，后续整理起来也方便

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by juestchaos** [comment]
2.x 开始支持 多文件和但文件模式，都不会ob 日记混合，你可以尝试
