### ISSUE TITLE
[Bug]: 当开启Obsidian的时候自动打开Memos。该功能打开后，仍然无法实现打开Ob的时候打开Memos。

### ISSUE THREAD

**Issue by Lin-Ye-Ye** [Quorafind/Obsidian-Memos#388]
### Bug Description

该功能异常。
<img width="960" alt="Snipaste_2024-01-22_18-26-27" src="https://github.com/Quorafind/Obsidian-Memos/assets/66284497/1f66aa01-5967-42e9-90bf-184445c346b2">

### Obsidian Version

v1.5.3

### Which editor are you using?

- [ ] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by juestchaos** [comment]
已经修复了，但在 2.2.1 中释放， 2.2.1 目前发版时间未定

**Comment by juestchaos** [comment]
2.2.1 已经释放，此问题已经修复
