### ISSUE TITLE
全局快捷键失灵

### ISSUE THREAD

**Issue by SrSh-notme** [Quorafind/Obsidian-Memos#395]
### Bug Description

设置全局快捷键无效。升级到 2.2.1 后，无法使用全局快捷键

### Obsidian Version

1.5.3

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by juestchaos** [comment]
2.2.3 已经修复并释放
