### ISSUE TITLE
[Bug][Thino]:微信同步的thino和obsidian直接记录的thino 保存位置不一致 

### ISSUE THREAD

**Issue by lostcrab9** [Quorafind/Obsidian-Memos#396]
### Bug Description

[Bug][Thino] 
插件设置了Thino保存位置为多文件，并且关闭了画布和单文件的开关。
但通过微信同步的thino依然会保存为单文件模式。
而在obsidian中写的thino会以多文件的形式保存。
不知道为什么？

### Obsidian Version

2.2.2

### Which editor are you using?

- [ ] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by juestchaos** [comment]
同步现在同步到其他端就是使用 单文件模式的
这个在同步功能发布上线会后，写在了说明中，包括为什么暂时要这么设计
