### ISSUE TITLE
[Bug]: 输入的过程中非常卡

### ISSUE THREAD

**Issue by jichunchi** [Quorafind/Obsidian-Memos#398]
### Bug Description

目前电脑端存在这个问题，特别卡特别慢，重启电脑和软件、换主题都试过了，还是很卡，不知道为什么（电脑是mac，ob和memos都是最新版）

### Obsidian Version

1.5.3

### Which editor are you using?

- [ ] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by juestchaos** [comment]
memos？版本
新版更名后 thino 没有这个问题了

**Comment by jichunchi** [comment]
> memos？版本 新版更名后 thino 没有这个问题了

我没有用thino 还是用的memos 需要用thino嘛

**Comment by juestchaos** [comment]
thino 没发现这个问题了，或者说 memos 2.x 之后这个问题没有什么反馈了
