### ISSUE TITLE
Tag list not recognizing emoji tags

### ISSUE THREAD

**Issue by ktubbs24** [Quorafind/Obsidian-Memos#40]
I entered this tag '#👭' into a memo note after some text and over in the tag list on the left it did not appear. Currently I am using this plugin on mobile when it did not show but not sure if the same is said for desktop.

**Comment by Quorafind** [comment]
It is werid that it works on my side. Could you give more information like screenshot of the plugin settings?

**Comment by Quorafind** [comment]
Hey, can you please try the latest version? Does this question remain after 1.7.12?
