### ISSUE TITLE
Hotkeys

### ISSUE THREAD

**Issue by javiavid** [Quorafind/Obsidian-Memos#5]
Is it possible that you add a hotkeys so that it is more comfortable to use?
Suggestion:

Ctrl + Enter - Noteit
Esc - Close Full Screen Image

Thanks

**Comment by FelipeRearden** [comment]
+1 for these hotkeys, specially CRTL/CMD+ENTER for Noteit :)

A great companion for #8

**Comment by Quorafind** [comment]
Ctrl + Enter is used by Obsidian itself though. Will figure a way to make it works.

**Comment by javiavid** [comment]
It would also be interesting to use the left and right cursors of the keyboard to move from one photo to another when you have the enlarged photo.

**Comment by FelipeRearden** [comment]
> Ctrl + Enter is used by Obsidian itself though. Will figure a way to make it works.

How about CRTL+SHIFT+ENTER or CRTL+ALT/OPTION+ENTER ? 👀

**Comment by javiavid** [comment]
I've been using memos for a few days and maybe it's not necessary this hotkey.
Pressing Tab and then ENTER it is possible to get to the Noteit button, it is very similar to making a 2-key combination.

**Comment by Quorafind** [comment]
Available in #90
