### ISSUE TITLE
Support suggesting all vault tags

### ISSUE THREAD

**Issue by wenlzhang** [Quorafind/Obsidian-Memos#51]
Currently, it seems that only tags within items that can be recognized by Memos, e.g. those within daily notes under the desired header and with the correct time stamp prefix, can be suggested.

It would be great if all tags from the entire vault can be suggested when using tag suggestion. Of course, this can be an option in the configuration pane, in case there are users that only want to get tag suggestions within daily notes.

**Comment by Quorafind** [comment]
An option will be good, available in next version

**Comment by Quorafind** [comment]
available in #115
