### ISSUE TITLE
Does not play well with other plugins in daily notes

### ISSUE THREAD

**Issue by brimwats** [Quorafind/Obsidian-Memos#52]
Here are my settingss 
![image](https://user-images.githubusercontent.com/73113656/150026738-7c4fc47a-ba00-4927-9d32-255aeb7b7355.png)

It should be posting under the heading ### Daily Memos, but

![image](https://user-images.githubusercontent.com/73113656/150026775-d9496c45-05dd-4e3e-8619-78942bb6e99d.png)

![image](https://user-images.githubusercontent.com/73113656/150026783-acd9710a-1456-4d49-9d7b-437a64ad8700.png)

**Comment by Quorafind** [comment]
Could you try to use # Daily Memos rather than ### Daily Memos? And could you send me debug info and the screen shot of Obsidian console? You can use ctrl shift i to call it.

**Comment by brimwats** [comment]
@Quorafind it doesn't:

![image](https://user-images.githubusercontent.com/73113656/150662719-cd232798-e388-4dc6-b010-2a300f6e39af.png)


it goes to the bottom bottom however and then doesn't appear in the memos sidething:
![image](https://user-images.githubusercontent.com/73113656/150662720-7a5f3fd5-c9e5-4c68-9dd5-e59bb7b04b4c.png)

like so:
![image](https://user-images.githubusercontent.com/73113656/150662744-0d240612-7d44-4e09-aa5d-297077eabda1.png)


settings:

![image](https://user-images.githubusercontent.com/73113656/150662754-3d03c71c-45e6-4e1e-bbcc-95405bc157e2.png)



debug:
SYSTEM INFO:
	Obsidian version: v0.13.21
	Installer version: v0.13.14
	Operating system: Windows 10 Education 10.0.22000
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: obsidian-theme-template
	Snippets enabled: 21
	Safe mode: off
	Plugins installed: 108
	Plugins enabled: 87
		1: Style Settings
		2: Activity Logger
		3: Advanced URI
		4: Auto Class
		5: Better File Link
		6: Buttons
		7: Calendar
		8: Checklist
		9: Citations
		10: Code Editor Shortcuts
		11: Collapse All
		12: Contextual Typography
		13: Customizable Menu
		14: Customizable Page Header
		15: Customizable Sidebar
		16: Cycle through Panes
		17: Dataview
		18: Folder Note Core
		19: Format Hotkeys
		20: Footnote Shortcut
		21: Flexible Pomodoro For Obsidian
		22: File path to URI
		23: File Info Panel
		24: File Explorer Note Count
		25: Enhancing Mindmap
		26: Editor Syntax Highlight
		27: Key Promoter
		28: Kanban
		29: Image Caption
		30: Icon Swapper
		31: Icon Shortcodes
		32: Hotkey Helper
		33: Find unlinked files and unresolved links
		34: Get Info
		35: Global Hotkeys
		36: Grandfather
		37: Graph Analysis
		38: Hider
		39: Homepage
		40: Highlightr
		41: Hover External Link Plugin
		42: LanguageTool Integration
		43: Link Archive
		44: Link Favicons
		45: Linked Data Vocabularies
		46: Linter
		47: Local images
		48: Macros
		49: MetaEdit
		50: Mind Map
		51: MySnippets
		52: Mousewheel Image zoom
		53: Natural Language Dates
		54: Obsidian Charts
		55: Obsidian Tabs
		56: Obsidian42 - Text Transporter
		57: Obsidian42 - BRAT
		58: Open with
		59: Plugin Changelogs
		60: Plaintext
		61: Periodic Notes
		62: Pane Relief
		63: Pandoc Plugin
		64: Quick Explorer
		65: Recent Files
		66: Related Notes Finder
		67: Reset Font Size
		68: Sentence Navigator
		69: Smarter Markdown Hotkeys
		70: Tag Page Preview
		71: Tag Wrangler
		72: Templater
		73: Timeline
		74: Toggle Readable Line Length
		75: Tweet to Markdown
		76: URI Commands
		77: Various Complements
		78: Webhook Plugin
		79: Word Sprint
		80: Supercharged Links
		81: QuickAdd
		82: Bartender
		83: Obsidian Leaflet
		84: Admonition
		85: Longform
		86: Another Quick Switcher
		87: Obsidian Memos

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.


there are no warnings or errors, just:

![image](https://user-images.githubusercontent.com/73113656/150662783-a72132b3-3afa-44a7-874f-a91e054826d6.png)

**Comment by Quorafind** [comment]
Fixed in next version, and i think the problem occurs because the `(+)`
