### ISSUE TITLE
Memos not recognising linked section names

### ISSUE THREAD

**Issue by rushikb** [Quorafind/Obsidian-Memos#53]
Love this plugin! Currently facing a problem where the plugin isn't recognizing Memos below a section header that is also linked. 
for example — I use the header # [[Journal]] as the top header under which all memos are saved — but these aren't being pulled in. However, using the same header name for INSERT_AFTER still works. 

I do plan to change the way my DNP works to remove headers with this sort of structure, but I really love the ability to also look at all previous memos. Would it be possible to offer multiple options for sections under which memos should be processed? would save a lot of time required to change each previous header name

![image](https://user-images.githubusercontent.com/6484525/150059251-953afd5a-900e-4e4f-b0bc-738183f8aba4.png)
![image](https://user-images.githubusercontent.com/6484525/150059257-30a2b8f9-7727-450c-b26a-98a30bbc908c.png)

**Comment by Quorafind** [comment]
Will check this soon, thanks for report, same with #18

**Comment by Quorafind** [comment]
Fixed in #55
