### ISSUE TITLE
Focus on input box when opening Memos on the Mobile

### ISSUE THREAD

**Issue by wenlzhang** [Quorafind/Obsidian-Memos#57]
I created a shortcut (it only contains an URI to Memos) for quickly opening Memos on iOS. Whenever I click the shortcut, it would automatically open Obsidian and load Memos UI. In a previous version of Memos, when I do this, it would automatically focus on the input box and pop up the keyboard, which I think is nice, as one can quickly capture ideas on the Mobile.

However, with version 1.4.1 of Memos, when I run this shortcut on iOS, it would load the Memos UI but wouldn't focus on the input box. One has to click the input box and then take notes. Therefore, it would be great if it can revert to the previous behaviour.

I am not sure if this change is related to the fact that one can set the input box to be at the bottom, though. Still, my use case is to put it at the top.

**Comment by hqweay** [comment]
Adding an option for this would be great. Some prefer to capture ideas, others just like a review...focus or not depending on preference.

**Comment by wenlzhang** [comment]
Another method to resolve this issue is to add a command like `Focus on Input Box`. Then the shortcut can use this command to open Obsidian, load memos, focus on the input box, and pop up the keyboard.

**Comment by Quorafind** [comment]
Already a command name focus on the Memos Editor in the pre version

**Comment by wenlzhang** [comment]
By "pre version", do you mean the latest version 1.4.3? With this version of Memos, I compared the two commands `Open Memos` and `Focus on Memos Editor` in the following two cases:

- Close Obsidian before running the commands
- Open a note in Obsidian and then make Obsidian running in the background before running the commands

For the first case, both commands give the same results, i.e. they would both go to the Memos UI, but the focus would not be in the input box. One needs to click the input box first, and then the keyboard would pop up.

For the second case, the first command would go to the Memos UI, but the result is the same as the first case; the second command would not load the Memos UI, and it would go to the previously opened note instead.

**Comment by Quorafind** [comment]
Fix in next version

**Comment by Quorafind** [comment]
Fixed in #60
