### ISSUE TITLE
Support searching for text with a search box

### ISSUE THREAD

**Issue by wenlzhang** [Quorafind/Obsidian-Memos#62]
Currently, one can look for desired memos by combining the usage of queries, tags, quick filters and dates, which is very powerful for searching for regular stuff.

On the other hand, it would make the searching more powerful if there can be another dimension, i.e. a search box. The use case for this search box can be searching for temporary stuff. It can be placed somewhere close to the quick filter box.

Within the search box, one can type any keywords and the results would change instantly, just like when using the methods mentioned above. The syntax for connecting multiple keywords can be something similar for defining queries or the native Obsidian syntax can be used, e.g. `keyword1 -keyword2` and `keyword1 OR keyword2`.

**Comment by Quorafind** [comment]
Did you mean the search bar at the top of memos?

**Comment by Quorafind** [comment]
![image](https://user-images.githubusercontent.com/13215013/150641896-bce1838f-7995-4123-b9b1-49c136a81f72.png)

**Comment by wenlzhang** [comment]
> Did you mean the search bar at the top of memos?

Thanks for the help! I just realized that I can type text in the box. 😅

Previously, whenever I hover the mouse there, it would pup up a box letting me select some quick filter. Therefore, I thought I had to select one of them.

It might be more user-friendly if the search box can be made more visible in case someone like me is using a white/light background. Just a thought.

**Comment by wenlzhang** [comment]
> The syntax for connecting multiple keywords can be something similar for defining queries or the native Obsidian syntax can be used, e.g. `keyword1 -keyword2` and `keyword1 OR keyword2`.

Since one can already search desired keywords in the box, this "more advanced search syntax" can make the temporary searching use case more powerful.

**Comment by Quorafind** [comment]
> It might be more user-friendly if the search box can be made more visible in case someone like me is using a white/light background. Just a thought.

How about adding animation when the mouse hover on it like this?

![image](https://user-images.githubusercontent.com/13215013/150661402-80e2fcef-5482-4554-afbb-f944e5f7c357.png)

**Comment by wenlzhang** [comment]
> How about adding animation when the mouse hover on it like this?

This would be great! It might be more helpful if there can be some box and text hint indicating that one can type something there.
![Memos](https://user-images.githubusercontent.com/44930227/150674892-76909630-0d66-48ec-9611-7ceb81821c1c.png)

**Comment by Quorafind** [comment]
available in #115
