### ISSUE TITLE
[Bug] The date(title) of one journal does not match with the heat map.

### ISSUE THREAD

**Issue by Kord64** [Quorafind/Obsidian-Memos#63]
For example, the journal titled 2021-01-10 displays Jan 11 in the heat map. 

![Screen Shot 2022-01-21 at 07 31 42](https://user-images.githubusercontent.com/93251479/150439560-8ac9b58c-3a54-4fa5-bd28-24cbbd91ed46.jpg)

However, the newest journal titled 2021-01-12 displays the correct date.

![Screen Shot 2022-01-21 at 07 31 57](https://user-images.githubusercontent.com/93251479/150439575-bad7393d-d1ee-4d59-b9d4-2751084acd97.jpg)

**Comment by Quorafind** [comment]
Will be fixed in next version
