### ISSUE TITLE
无法在记录框直接输入中文

### ISSUE THREAD

**Issue by Dirtyuri** [Quorafind/Obsidian-Memos#65]
![Memos报错信息](https://user-images.githubusercontent.com/68465099/150452851-70be2913-342b-4624-ba41-f060e9a79b40.jpg)
问题如标题所述，报错信息见上图。已尝试关闭所有片段和插件（包括Periodical Notes）、设置日记文件夹路径等等，均无效，恳请再想想解决办法，感谢！

**Comment by Quorafind** [comment]
查看自己是否设置日记插件的路径，如果不是的话，那么关闭所有片段和插件后，开启日记插件，再重启一下 Ob

**Comment by Dirtyuri** [comment]
> 查看自己是否设置日记插件的路径，如果不是的话，那么关闭所有片段和插件后，开启日记插件，再重启一下 Ob

试过了，确认无效...

**Comment by Quorafind** [comment]
Ctrl+P 输入显示调试信息以后，复制粘贴到这里给我看一下？

**Comment by Dirtyuri** [comment]
> Ctrl+P 输入显示调试信息以后，复制粘贴到这里给我看一下？

SYSTEM INFO:
	Obsidian version: v0.13.19
	Installer version: v0.12.19
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Blue Topaz
	Snippets enabled: 11
	Safe mode: off
	Plugins installed: 69
	Plugins enabled: 64
		1: Hotkeys for starred files and searches
		2: Hotkeys for specific files
		3: Citations
		4: CardBoard
		5: MetaEdit
		6: cMenu
		7: Periodic Notes
		8: Calendar
		9: CodeMirror Options
		10: Collapse All
		11: Copy Block Link
		12: Customizable Menu
		13: Customizable Sidebar
		14: Excalidraw
		15: Emoji Shortcodes
		16: Dataview
		17: Drag and Drop Blocks
		18: Force note view mode
		19: Footnote Shortcut
		20: Folder Note Core
		21: Get Info
		22: Graph Analysis
		23: Hider
		24: Hotkey Helper
		25: Quick Switcher++
		26: QuickAdd
		27: Pandoc Plugin
		28: Pane Relief
		29: Obsidian42 - BRAT
		30: Obsidian42 - Text Transporter
		31: Natural Language Dates
		32: NLP
		33: Note Refactor
		34: Obsidian Big Calendar
		35: Kanban
		36: Longform
		37: Recent Files
		38: Remember cursor position
		39: Reminder
		40: Show Current File Path
		41: Style Settings
		42: Supercharged Links
		43: Tag Wrangler
		44: Tasks
		45: Templater
		46: Tidy Footnotes
		47: Typewriter Scroll
		48: Various Complements
		49: ZH增强编辑
		50: Obsidian Memos
		51: Workspaces Plus
		52: Zoom
		53: Commits
		54: Outliner
		55: Breadcrumbs
		56: BookNote
		57: Block Reference Counter
		58: BibNotes Formatter
		59: Better footnote
		60: Banners
		61: AidenLx's Folder Note
		62: Advanced URI
		63: Admonition
		64: Activity History

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please try to make the issue happen in the help vault or disable community plugins.

**Comment by Quorafind** [comment]
你可以尝试用新的库来测试一下是否是运行环境的问题吗

**Comment by Dirtyuri** [comment]
> 你可以尝试用新的库来测试一下是否是运行环境的问题吗

换了个库，也不能输入中文，看来是我电脑系统（win11）的问题了...我就这么用吧，先录入一个英文字符或标签，再切换成中文，辛苦大大了！

**Comment by Quorafind** [comment]
@Dirtyuri 等后续我装一个 Win11 去测试一下，因为我的现在手上没有 Win11 设备，不好意思。

**Comment by kimonoki** [comment]
我在win10上也有这个问题，小狼毫无法直接输入，需要先打个其他字符
