### ISSUE TITLE
安卓上memos内容无法正常显示

### ISSUE THREAD

**Issue by hok8746** [Quorafind/Obsidian-Memos#68]
输入内容后只会记录在日记中。不会出现在memos的界面上，热力图上也没有。并且以前的日记中符合memos格式的内容也不能识别进memos。而如果成功输入内容后第二条memo会把第一条覆盖掉，或者切换界面再进入memos中刚刚记录的内容也会在memos上消失。

https://user-images.githubusercontent.com/98163114/150532544-9b788497-3f8f-4ffd-ac07-755cce282ab1.mp4

https://user-images.githubusercontent.com/98163114/150532585-0d6d6a81-6162-49c9-a936-676b56cd6317.mp4

**Comment by hqweay** [comment]
我记得有个版本更新后会出现这个问题，你检查下 setting 里的 Process Memos below 和 日记源md 文件是否一致呢。

**Comment by Quorafind** [comment]
请将 Process Memos Below 和 Insert After 的选项设置成一致，下个版本我会加上不一致的提示
