### ISSUE TITLE
[Bug] Adding a tag through suggested tags would delete the text after it, but within the line / paragraph. 

### ISSUE THREAD

**Issue by Kord64** [Quorafind/Obsidian-Memos#71]
## Steps to Reappear

1. Insert a tag before some text within the line / paragraph, by pressing Enter to select from suggested tags. 
2. The tag is auto-filled but the text after it is deleted.

![Screen Recording 2022-01-22 at 21 38 58](https://user-images.githubusercontent.com/93251479/150640917-7559f6d9-0827-4cce-a572-513a968ad484.gif)

**Comment by Quorafind** [comment]
Fixed in next version

**Comment by Kord64** [comment]
Besides this plug-in so far does not recognize two line breaks as the next line / paragraph, which is `<br><br>` in the markdown file. However two line breaks with an extra space mark would do visually, which is `<br> <br>`. ❤️

**Comment by Quorafind** [comment]
Fixed in #90
