### ISSUE TITLE
Did MemoEditor compile successfully?

### ISSUE THREAD

**Issue by hqweay** [Quorafind/Obsidian-Memos#72]
I just found the image uploader is still not working on iOS. The `document.body.appendChild(inputEl);` not in the main.js.(I checked 1.7.1, 1.3.4, etc)   #46 

<img width="686" alt="image" src="https://user-images.githubusercontent.com/23608642/150650320-a4e5bfd1-84c5-475f-87bd-520126d33b59.png">

So I try to compile the project on my computer, It failed.

<img width="797" alt="image" src="https://user-images.githubusercontent.com/23608642/150650151-c67487f5-198c-4a24-8af9-98452f108e6d.png">

When I commented out this line of code, it compiled successfully, and the `document.body.appendChild(inputEl);` in the main.js.

<img width="417" alt="image" src="https://user-images.githubusercontent.com/23608642/150650113-df47ff23-18c1-42f1-b780-24fcf9d44a60.png">

<img width="404" alt="image" src="https://user-images.githubusercontent.com/23608642/150650248-83a6dd71-e2fe-4ae8-8c15-56c6615cfd7d.png">

I'm not sure if there is a problem here?

**Comment by Quorafind** [comment]
LOL, I forgot to insert it into my dev code. Sorry, could you try the lastest version to see if the error remains?

**Comment by hqweay** [comment]
> LOL, I forgot to insert it into my dev code. Sorry, could you try the lastest version to see if the error remains?

Thanks for your work, 1.7.3 works well.
