### ISSUE TITLE
 img-picker UI issue on iOS/mobile phone

### ISSUE THREAD

**Issue by hqweay** [Quorafind/Obsidian-Memos#76]
When I have added an image, the img-picker is displayed on the bottom left on iOS.

I’m not sure it's a mobile device Ui bug or an iOS issue.

![07805E47-7FAB-4421-919B-002BED4B6065](https://user-images.githubusercontent.com/23608642/150664229-8bec0124-347a-467a-b52d-d7fbc43aed00.png)

![FC8E50E1-C3F5-407B-B9DD-C6D90D1F0662](https://user-images.githubusercontent.com/23608642/150664244-d908f1bb-0950-4096-bec4-631cbc6585b5.jpeg)

**Comment by Quorafind** [comment]
When you leave memos, is it still remain?

**Comment by hqweay** [comment]
> When you leave memos, is it still remain?

yes, I switched to other notes, it is still there.

![1DFEE15D-E40B-43D3-AD26-20B6F8628392](https://user-images.githubusercontent.com/23608642/150665009-cebc2aa9-79cf-4011-a241-44f7da1eb135.png)

**Comment by hqweay** [comment]
Maybe it occurs by ‘document.body.appendChild(inputEl);’ not removed...🥲
