### ISSUE TITLE
[Feature Request] Caret Cursor on What Do You Think Now

### ISSUE THREAD

**Issue by FelipeRearden** [Quorafind/Obsidian-Memos#8]
Hello @Quorafind !!!!

When opening the Memo, would be great if the caret cursor were already set in the What Do You Think field .

This way, I can automatically start to type :) 

Today
![0](https://user-images.githubusercontent.com/85180696/148204142-d1121d4f-12da-424a-b4d3-c1ef9afb79a4.png)

My FR
![1](https://user-images.githubusercontent.com/85180696/148204174-0d70f19e-4d5b-4b34-ba3f-a494060eaf97.png)

Thanks for reading this :)

Have a great day!

**Comment by Quorafind** [comment]
Good idea, will be added in next version

**Comment by FelipeRearden** [comment]
> Good idea, will be added in next version

Thank you very much!!!

**Comment by Quorafind** [comment]
Available in #13

**Comment by FelipeRearden** [comment]
> Available in #13 

Working perfect on version `1.0.5` Obsidian `0.13.14`
