### ISSUE TITLE
Rime (a Chinese input method) cannot work well

### ISSUE THREAD

**Issue by cshishaliu** [Quorafind/Obsidian-Memos#87]
OS: macOS Monterey 12.1
Device: MacBook Pro 14' (2021)

输入框中没有字符时, 无法用 RIME 输入法在其中输入第一个汉字。macOS 自带的中文输入法没有这个问题。

https://user-images.githubusercontent.com/2427830/150911289-b11b136d-9e67-4cec-b404-cbdeabdcf4c7.mov

**Comment by Quorafind** [comment]
你可以尝试一下在右上角的输入框输入一下中文吗，看看能不能正常输入

**Comment by Quorafind** [comment]
类似的，有社区用户反馈在 Win 下， Rime 输入法能正常运作

**Comment by Quorafind** [comment]
如果有更多的相关信息，请重新开启 issue 。

**Comment by ASC8384** [comment]
> 类似的，有社区用户反馈在 Win 下， Rime 输入法能正常运作

您好，使用 Obsidian 1.4.13，插件最新版本，小狼毫（Rime的Windows构建版本）v0.15.0，不能输入。

切换到微软输入法后随便输入几个中文字，再切换回小狼毫后，可以用小狼毫打字，但是一旦发送后小狼毫就无法输入了。
