### ISSUE TITLE
Aside panel still displays in dark mode when Memos are pinned to sidebar

### ISSUE THREAD

**Issue by VeroVerro** [Quorafind/Obsidian-Memos#88]
Hi, thank you for the wonderful plugin! I found a small bug with the css though - in dark mode, the `display: none` for the aside for when memos are pinned to the sidebar gets overwritten by a `display: flex`:

![image](https://user-images.githubusercontent.com/17042871/150949122-c40c43ee-e1f7-4bc4-9f92-2b1998c075d9.png)

**Comment by Quorafind** [comment]
Fixed in next version. Soon

**Comment by VeroVerro** [comment]
Thank you!

**Comment by Quorafind** [comment]
Fixed in #90
