### ISSUE TITLE
希望增加按日历-日期跳转功能

### ISSUE THREAD

**Issue by AiurArtanis** [Quorafind/Obsidian-Memos#89]
### 需求背景

最近正在迁移来自印象笔记的旧笔记（1000+），很多内容都会当作之前的随手memo存下来。考虑到memos的特性是可以识别日记中的 ` - hi:mm  ` 开头的文字，所以把很多旧笔记都转成了memo的格式。但是因为笔记的时长跨度很大，靠点月份跳转（calendar也不支持按日期跳转）的方式太慢，所以希望memos在弹出daily memos窗口后，日期控件支持类似输入yyyy-mm-dd的形式跳转日历的功能。

### 本机环境

os：win10
obsidian：v0.13.19
ob-memos：1.7.6

## 其他

有几个问题还是希望bon大佬能回答一下：

1. **“中文”选项无效**    没看到哪里的UI替换成了中文，具体是需要怎么设置？
2. memos界面左侧的筛选栏下是否可以增加一个check列表的筛选

**Comment by Quorafind** [comment]
问题1答案，因为我还没有把字段翻译成中文
问题2答案，左侧筛选栏可以直接加一个是否是todo项目的筛选项

日历的建议，后续会支持选择年月份

**Comment by AiurArtanis** [comment]
问题1，2收到，多谢大佬
