### ISSUE TITLE
[Feature Request] Hotkey for Open Daily Memo

### ISSUE THREAD

**Issue by FelipeRearden** [Quorafind/Obsidian-Memos#9]
Hello @Quorafind !!!!

Would be amazing to have a hotkey to Open the Daily Memo Window with a keyboard hotkey :)

![2](https://user-images.githubusercontent.com/85180696/148204799-3a233d79-a3c3-446d-b7ac-f9d00513df31.png)

## Additional Request (if possible) :pray: 

New Command Palette: Obsidian Memos: Open Today Daily Memos

This new command would open Obsidian Memos window + Open Daily Memos Window

---

Thanks for reading this :)

Have a great day!

**Comment by Quorafind** [comment]
Will added some hotkey as far as I can.

**Comment by FelipeRearden** [comment]
> Will added some hotkey as far as I can.

Thank you very much :)

**Comment by Quorafind** [comment]
Available in #13

**Comment by FelipeRearden** [comment]
> Available in #13 

Working perfect on version `1.0.5` Obsidian `0.13.14`
